- engines/rbd.c
Running multiple concurrent RBD jobs can result in a segfault
attempting to retrieve the RBD AIO completion status from a
prematurely released fio_rbd_iou object.
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
> engines/rbd: potential re-use of active fio_rbd_iou

- memory.c
- options.c
- thread_options.h
This is primarily useful for benchmarking DAX files. If they are mmaped
with the MAP_PRIVATE flag they will still have copy on write semantics
and the test will not actually run against the memory that backs the
DAX file. This memory option allows tests to be constructed that use the
MAP_SHARED flag which allows running directly with the memory backing
a DAX file.
> Add mmapshared option to use mmaped files with the MAP_SHARED flag.

- iolog.h
Given the main.cc source file:
```
#include <fio.h>
int main() { return 0; }
```
And the gcc command line:
```
$ gcc main.cc -Ifio
In file included from fio/stat.h:4:0,
from fio/thread_options.h:7,
from fio/fio.h:18,
from main.cc:1:
fio/iolog.h: In function 'io_sample* __get_sample(void*, int, uint64_t)':
fio/iolog.h:125:53: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
return samples + sample * __log_entry_sz(log_offset);
^
fio/iolog.h:125:17: error: invalid conversion from 'void*' to 'io_sample*' [-fpermissive]
return samples + sample * __log_entry_sz(log_offset);
```
Building as c++ is useful for external engines, such as the ceph objectstore engine (https://github.com/ceph/ceph/pull/5943).
> iolog: fix error when compiled as c++

- smalloc.c
option --alloc-size isn't used, pools always have INITIAL_SIZE size
> use option smalloc_pool_size

- io_u.c
In io_u_log_error, the duplicated log call looked strange, this patch is a guess at original intent.
> Log to parent instead of twice to child td

- tools/fiologpaser.py
This tool lets you parse multiple fio log files and look at interval statistics even when samples are non-uniform.  For instance:
"fiologparser.py -s *bw*" to see per-interval sums for all bandwidth logs or:
"fiologparser.py -a *clat*" to see per-interval average completion latency.
Signed-off-by: Mark Nelson <mnelson@redhat.com>
> added fio log parser tool.

- Makefile
The Makefile for building with libhdfs is fixed to amd64, which makes failure on ppc64le arch.
> The fixed CPU architecture in the Makefile will make failure on ppc64le.

- stat.c
Kept original value for backward compatibility.
> Added millisecond-accurate timestamp to JSON output

- rate-submit.c
- workqueue.h
Given the main.cc source file:
```
#include <fio.h>
int main() { return 0; }
```
And the gcc command line:
```
$ gcc main.cc -Ifio -DCONFIG_HAVE_BOOL
In file included from ./ioengine.h:10:0,
from ./iolog.h:7,
from ./stat.h:4,
from ./thread_options.h:7,
from ./fio.h:18,
from main.cc:1:
./workqueue.h:19:8: error: expected unqualified-id before ‘private’
void *private;
^
./workqueue.h:19:7: error: expected ‘;’ at end of member declaration
void *private;
^
./workqueue.h:19:15: error: expected ‘:’ before ‘;’ token
void *private;
^
```
Building as c++ is useful for external engines, such as the ceph objectstore engine (ceph/ceph#5943).
> workqueue: rename private to priv for compiling as c++

- stat.c
Every time we set iolog->avg_last, we get a slight time drift. Namely we are taking samples *at least* every log_avg_msec milliseconds. This PR adjusts for the drift by subtracting the amount we drift by when updating avg_last.
> gaps in IOPS logs because of time drift

- options.c
I found that the rest of the jobs did not stop after a job terminated with an error while _exit_on_all_ was enabled.
So I fixed _options.c_ so that _exitall_on_error_ could work as specified.
> Fix "exitall_on_error" option

- engines/rbd.c
Fix memory leak in _fio_setup_rbd_data().
Signed-off-by: Jevon Qiao <scaleqiao@gmail.com>
> Fix memory leak in _fio_setup_rbd_data()

- engines/rbd.c
For segmentation fault issue:
Fio with rbd engine will panic if clustername option is specified but clientname
is not. In that case, o->client_name will be a NULL pointer, strlen(o->client_name) in _fio_rbd_connect() will lead to the segmentation fault.
For memory leak issue:
When running fio with rbd engine and specifying clustername, a piece of
memory will be allocated in _fio_rbd_connect(), but it never gets freed.
> Fix segmentation fault and memory leak issue in rbd engine

- gettime.c
I have been following issue ( #183 ), and found the root cause.
If the value of 'log_avg_msec' is relatively large (maybe greater than 1000), the computed interval time in _mtime_since_ overflows.Then the values of bw and IOPS are set to zero by the overflow. 
I confirmed this fix have resoloved the issue ( #183 ).
> Fix overflow caused by signed long division by unsigned long.

- iolog.c
- iolog.h
- stat.c
- stat.h
- tools/hist/fiologparser_hist.py
by tracking a linked-list of the most recent histogram and differencing it when we print to the log file(s). Linked list of pointers used to minimize runtime impact on recording side, instead choosing to do subtraction on the logging (when logs get printed to file) side.
This helps cleanup `fiologparser_hist.py`, makes the log files easier to understand at a glance (the frequencies correspond to just that interval), reduces file size(s), and averts the possibility of integer overflow in the logs (for a long enough fio job).
I couldn't get the existing linked list implementation to work for me (`flist.h`), but I can try again / rework this to use that if that's preferred. All I needed was a write-once, read-once singly-linked list.
> Make histogram samples non-cumulative

- HOWTO
- backend.c
- cconv.c
- fio.1
- fio.h
- fio_time.h
- libfio.c
- options.c
- rate-submit.c
- stat.c
- thread_options.h
- time.c
This adds an option to output Unix timestamps instead of zero-based ones.
This makes it easier to analyze the data in the context of other benchmarking tools running at the same time as fio.
> Unix epoch in log files

- client.c
- init.c
- iolog.c
- iolog.h
- server.c
- server.h
If I did this right, it should only affect fio when `--write_hist_log` is given.
Things I'm not sure I've done fully:
- Network byte order conversions
- Does the server version get updated, or is that just between releases?
For now without zlib present, this prints an error in client/server mode.
This code is working for me / my code question on the mailing list is solved (see commit message).
> Client / server code for handling histograms

- configure
- engines/rbd.c
Hi,
In Aug. 2015, a new function rbd_poll_io_events is added in Ceph. I use it to speed up io retrieval. I tested by using P3700 SSD and ceph_jewel(bluestore), find the iops and latency has 10% improvement.
> use poll() and rbd_poll_io_events to speed up io retrieval.

- oslib/libmtd.c
tmp_buf is allocated but not free'd, causing a minor memory leak
Signed-off-by: Colin Ian King <colin.king@canonical.com>
> Fix memory leak on tmp_buf

- backend.c
- cconv.c
- client.c
- eta.c
- fio.h
- gettime.c
- init.c
- io_u.c
- ioengines.c
- iolog.c
- iolog.h
- mutex.c
- options.c
- server.c
- server.h
- stat.c
- stat.h
- thread_options.h
Follow on from https://github.com/axboe/fio/pull/275 . Contains:
* Contains fixes from #275 .
* Improvements to ETA estimation when in ramp time and when switching from ramp time to normal time.
* Fixes to silence some compiler warnings.
* Rework how io_sample's union is accessed/used to silence warning on Windows.
* Bump server protocol version (not 100% sure if this is needed but you never know...)
> Miscellaneous fixes

- blktrace.c
- iolog.c
- iolog.h
Example patch for adding replay scaling to iolog replay and also fixes up a 64 bit number truncation issue in `iolog.c` too.
Not really a final version but more to get comment/ideas on how to add this in such a way that  `ipo_bytes_align()` can also be shared between `blktrace.c` and `iolog.c`.
> iolog: add support for 'replay_scale'

- HOWTO
- README
- options.c
- Change some parameter types to be time in the HOWTO.
- Put a space before the end of sentence but after links in the README.
- Update the Red Hat fio package information.
> doc: minor documentation changes

- iolog.h
The previous code was immediately returning on a positive alignment value, and accepting only alignment to zero.
I believe this should be doing the opposite.
> iolog replay_align fix

- configure
macOS 10.12 introduced support for clock_gettime() but when compiling
with Xcode 8 (or later) and targeting 10.11 (or older) the clock_gettime
symbol is now found at configure/compile time but referenced weakly.
Running the created binary on 10.11 results in a "dyld: lazy symbol
binding failed: Symbol not found: _clock_gettime" error.
This drama has played out across other projects:
- https://github.com/Homebrew/homebrew-core/issues/2674
- https://github.com/curl/curl/issues/1069
- https://svn.filezilla-project.org/filezilla?view=revision&revision=7824OO
- https://github.com/mesonbuild/meson/pull/949
- https://github.com/Homebrew/homebrew-core/issues?utf8=%E2%9C%93&q=label%3Aclock_gettime%20
Options for working around this issue include:
1. Turn references to functions that might be weak …
> configure: try to disable weak linking on OSX

- .travis.yml
- Makefile
- Add a "test" target to the Makefile which runs two simultaneous null ioengine jobs for a short time.
- Make travis run two parallel make jobs letting it finish faster.
- Add two OSX builds to travis (with a third build commented out). This is slightly controversial because at peak time travis is heavily backed up with OSX builds from other projects. This can mean the travis results don't return in the usual less than 4 minutes but can instead take up to 2 hours(!) because while the Linux jobs were scheduled quickly the OSX ones weren't. If this sounds problematic, perhaps I can rework this commit to just comment out the travis OSX builds...
> Add make test and add OSX builds to travis

- appveyor.yml
Add AppVeyor (https://www.appveyor.com/ )  continuous integration build of the Windows port (you'll need an AppVeyor account to get going) . The 64 bit and 32 bit versions of the Window's binary are currently built. This also builds the Windows installer and the resulting MSI can be downloaded. Example output can be seen on https://github.com/sitsofe/fio/commits/appveyor and https://ci.appveyor.com/project/sitsofe/fio/build/1.0.37/job/c3i3jw3ug8bdt5pq . At the moment builds seem to be scheduled in under a minute.
Note that AppVeyor limits you to one build at a time but each build seems to finish after about one minute so the total time to get a result is about 3 minutes.
> appveyor: add CI building of the Windows version of fio

- parse.c
Fix overflow that happened when using the 'd' time suffix on platforms
with 32 bit longs which led to a time of less than 10 minutes being
used.
> fio: fix overflow trying to use 'd' suffix

- HOWTO
- Makefile
- engines/e4defrag.c
- engines/ftruncate.c
- examples/ftruncate.fio
Hi,
Fio was designed to be swiss knife for io performance testing, but it is appeared to be good stress testing tool too. For that reason it is good to have such things as truncate.
BTW: If you do not mind I also  would like to add more engines for zero_range,insert_range, collapse_range ioctls.
> Add truncate engine

- engines/rbd.c
Signed-off-by: Pan Liu <wanjun.lp@alibaba-inc.com>
> remove redundant _fio_rbd_disconnect, which is already called in fio_rbd_cleanup

- configure
- flist.h
`stddef.h` is provided by the compiler and has a builtin `offsetof` implementation if it is available. For instance, both GCC and Clang have the following (or very similar):
```C
#define offsetof(t, d) __builtin_offsetof(t, d)
```
> flist.h: replace offsetof macros by stddef.h include

- os/os-android.h
As noted by @enh on #352, the current fix doesn't work for Android O (API level 26). This allows things to work again (by not including `<sys/shm.h>` and defining the single thing needed from it manually).
> os/os-android.h: fix compilation for Android O

- os/os-android.h
Fixes: #356 ("Android: SIGBUS due to unaligned access")
Signed-off-by: Omri Mor <omor1@asu.edu>
> os/os-android.h: fix alignment problems in shared memory functions

- fio.h
- libfio.c
- stat.h
Fix unaligned/misaligned accesses related to struct thread_stat and
struct jobs_eta seen when running a build produced by
CC=~/clang-3.9/build/bin/clang ./configure --disable-optimizations \
--extra-cflags="-D__compiler_offsetof=__builtin_offsetof \
-fsanitize=undefined"
and add to the compile time asserts to make these problems more visible.
> fio: fix some struct alignment issues

- HOWTO
- fio.1
- stat.c
The first commit finishes off the group percentage fix from a previous commit. The second changes the documentation to state that random_distribution's parameter for a Gaussian distribution is called
"normal" (but curiously file_service_type uses "gauss" for its Gaussian distribution parameter)
> stats and documentation fixes

- .travis.yml
- HOWTO
- arch/arch-arm.h
- doc/fio_examples.rst
- examples/butterfly.fio
- filesetup.c
- fio.1
- gettime.c
- init.c
- options.c
- os/os-dragonfly.h
- os/os-freebsd.h
- os/os-netbsd.h
- os/os-openbsd.h
- os/os.h
Mostly minor documentation fixes but also contains a fix for a BSD PPC issue mentioned in https://svnweb.freebsd.org/ports/head/benchmarks/fio/Makefile?revision=445762&view=markup , tries to make the ARM failure mentioned in SVN link more obvious, makes the clocksource chosen a bit easier to see when debug options are on and fixes fio failing to create files on Windows.
> Minor fixes

- filesetup.c
if set direct=1, but fs not support direct io, should use O_DIRECT when
pre-allocte test file, otherwise file open success and then fallocate
will alloc memory for it.
Signed-off-by: weiping zhang <zhangweiping@didichuxing.com>
> filesetup: keep O_DIRECT flag same as test  when pre-allocte file

- HOWTO
- backend.c
- cconv.c
- fio.1
- init.c
- iolog.c
- options.c
- thread_options.h
If this isn't set (the default) fio can submit asynchronous I/Os that
overlap leading to potential data races. When this option is set, the
race is avoided by having fio serialize the overlapping submissions.
Thanks to Rachel Lunnon (StorMagic) for helping me debug the initial
version of this!
> Add serialize_overlap option

- .travis.yml
- Makefile
- appveyor.yml
Add a commits that ensure `make test` includes something that tries to use a file on a real filesystem and make CI builds abort on compiler warnings.
> Enhance continuous integration builds

- time.c
Commit 8b6a404cdd2c40715885e562416c3db039912773 ("nanosecond: initial
commit changing timeval to timespec") introduced a change to
timespec_add_msec that decreased the time to (unsigned) overflow of
adj_nsec leading to strange values in the write_*_log files when using
log_avg_msec. The following fio job reproduces the problem:
./fio --ioengine=null --size=2G --time_based --runtime=11s \
--ramp_time=5s --write_iops_log=overflow --log_avg_msec=5000 \
--name=overflow
cat overflow_iops.1.log shows the following:
5000, 997853, 0, 0
10640, 141323, 0, 0
Compiling fio with clang's undefined behaviour
sanitizer with unsigned wraparound detection turned on by using
CC=clang ./configure --extra-cflags="-fsanitize=undefined,integer"
and running the previous job produces a lot of false positives but …
> time: fix overflow in timespec_add_msec

- stat.c
**plat_idx_to_val()** in stat.c has a variable base that is defined as an
unsigned int but it was designed to fit old settings where
FIO_IO_U_PLAT_GROUP_NR = 19.
However, with the alteration from usec to nsec in commit d6bb62 
(nanosecond: update completion latency recording and normal, json 
output to use nanoseconds), FIO_IO_U_PLAT_GROUP_NR is now 29 
and the range of latency changed from uint32_t to uint64_t. 
This means variable base can easily exceed a 32-bit range 
and overflow after error_bits reaches 26.
Eg
Group Id | MSB | discarded error_bits | range of value
------------ | ------------- | ------------ | -------------
27 | 32 | 26 | [4294967296, 8589934591]     
28 | 33 | 27 | [8589934591, 17179869183]
29 | 34 | 28 | [17179869184, +inf]
It should be like this if I'm not getting …
> stat: increase the size of base to avoid overflow

- HOWTO
- fio.1
Commit 5bba8b3acee1bf1359470a82cac030942018405a ("Remove '--runtime'
command line option") removed the --runtime option from the fio tool and
its internal help. This commit removes it from the documentation files
too.
> doc: remove '--runtime' command line option

- filesetup.c
Fix for layout not working when it has to make a file with `direct=1` on Linux due to memory not being aligned and an additional warning about `direct=1` not being liked if direct layout fails with EINVAL.
Still waiting for feedback via https://github.com/axboe/fio/issues/429 but creating the pull request now so I don't forget about it after feedback arrives.
> Direct layout fix

- arch/arch-ppc.h
Mark condition register 0 (cr0) as being clobbered by the inline asm in
the ppc version of get_cpu_clock(). Not doing this results in strange
behaviour due to GCC optimising away some checking. For example:
$ ./fio examples/null.fio --output-format=json
time     5500  cycles_start=8085227422910      <--- bad!
{
"fio version" : "fio-2.21-89-gb034",
<snip>
The extra output is due to the flag checking in dprint being removed
at higher optimisation levels.
Signed-off-by: Oliver O'Halloran <oohall@gmail.com>
> arch/ppc: Fix get_cpu_clock asm clobber list

- init.c
Try to make the "multiple jobs overwriting same file" warning more specific to address https://github.com/axboe/fio/issues/303 and add a new warning about the verify phase not running when using runtime + time_based (see https://github.com/axboe/fio/issues/187#issuecomment-223633831 and https://www.spinics.net/lists/fio/msg04990.html ).
These commits are kind of for review: for example if the user is using rw=rw / rw=randrw with their verify they may also get inline verifies because if at the point an area is read if it matches an area previously written by the same job it is verified. I wasn't sure if the skipping the warning in this situation when the user has asked for do_verify was worth it...
> Verify warn

- iolog.h
- stat.c
When using log_avg_msec and multiple I/O directions, the results
recorded for the directions other than the first are attributed to the
wrong time. This is demonstrated by the following:
sudo modprobe null_blk completion_nsec=100000000 irqmode=2
sudo ./fio --bs=4k --direct=1 --ioengine=libaio --log_avg_msec=1000 \
--runtime=2s --disable_lat=1 --disable_bw_measurement=1 \
--filename=/dev/nullb0 --write_iops_log=shiftedlog --rw=rw \
--name=shiftedlog
results in this:
cat shiftedlog_iops.1.log
1000, 5, 0, 0
2000, 6, 0, 0
2000, 4, 1, 0
2256, 4, 1, 0
shiftedlog_iops.1.log is missing an entry at 1000ms for for the write
direction (1) because the sample has been misattributed to 2000ms (the
third row) due to iolog->avg_last being shared by all directions.
Fix the shifting by turning …
> stat: fix shifted windowed logging when using multiple directions

- engines/glusterfs.c
- engines/glusterfs_async.c
On 32 bit systems compiling the gluterfs ioengine would generate some printf specifier warning so try and silence with macros and casts.
> glusterfs: silence printf specifier warnings

- .travis.yml
Get Travis to build a 32 bit fio (although sadly the one engine that would have benefitted the most from this (glusterfs) has a dependency that is not multilib compatible), minor Travis file reformatting and up the version of Xcode the OSX build targets.
> travis: add 32 bit build, minor updates and cleanups

- backend.c
- server.c
Clear the trigger_timeout after we have found it has been exceeded in
trigger_timedout() to stop us repeatedly firing the trigger again and
again in the future.
When --trigger-remote is unset, the server winds up with the remote
trigger command represented by buf[] being zero length rather than buf
being NULL in handle_trigger_cmd(). Cope with this by returning right
away if we find the cmd string is NULL or empty in exec_trigger().
Make server mode fio terminate after sending the verify state back to
the client so it goes on behave the same way as standalone fio. This
stops the while loop in thread_main() restating and in turn prevents
state being cleared away by clear_io_state().
Make keep_running() return false if td->terminate has been set Just In
Case.
The below would trigger the …
> backend: verify-trigger fixes

- os/os-solaris.h
This pull request addresses an issue which was mentioned a number of times now. First mention was in https://github.com/axboe/fio/issues/46. It was just yesterday updated: https://github.com/axboe/fio/issues/46#issuecomment-328369445
I believe this problem arises due to incorrect ID type used in os-solaris.h. This fix attempts to rectify this. I tested with dtrace before and after to confirm that in fact outcome is different before change after change.
Below are results, before and after making this minor change. Result value we expect to be 0 in all instances. We observe a couple of different error codes in the before test, and they correspond to the following strings observed at the time a job is started.
```
clock setaffinity failed: Operation not supported
...and...
clock setaffinity …
```
> Clock setaffinity problem on Solaris and Friends

- HOWTO
- fio.1
Jens, please consider these two patches that add a brief description of the JSON output format and emphasize that --status-interval does not provide per-period output.
Thanks to @sitsofe for feedback on the initial version of these patches.
> Small documentation changes

- engines/null.c
- examples/cpp_null.fio
- file.h
- ioengines.c
- lib/types.h
I successfully built a cpp io engine after a few small code changes. This patch reflects what I had to do and additionally wraps null engine with dummy C++ class as a form of test. I was able to built it with g++4.8 and clang 3.4.
> Adjustments to support C++ engines

- fio.1
While trying out a large-ish fio test in a machine with 4 GB of RAM, `fio` ran out of shared memory by a small amount.  After checking with `strace` for clues, I've noticed the probing for shmem.  The system could accomodate using 64 MB instead of ~33 MB (auto-tuned by the kernel).  `fio` ran happily.
> Add note for increasing shmmax if necessary

- appveyor.yml
- configure
The first change makes Appveyor install zlib for the Windows CI builds and does some cleanups. The good news is that it is has always been possible to download the builds that Appveyor makes (e.g. here a 3.0 MSI https://ci.appveyor.com/project/axboe/fio/build/1.0.263/job/304hphqrbcos4tk0/artifacts ) so this makes those builds more useful (as well as serving as an example of how to zlib fio building on Windows) if someone wants more pre-built fio Windows builds. The bad news is that it slows the combined time for all the Windows builds to complete down by about 30 seconds and it hard codes a mirror site (but that seems to be the site that other Appveyor Cygwin projects use).
The second commit is more finicky and showed up with the change to only use Cygwin64. Basically it changes how we …
> CI and configure changes

- gettime.c
Compiling fio with clang's undefined behaviour sanitizer and unsigned
wraparound detection enabled on a 32 bit Linux build turned up the
following:
gettime.c:313:28: runtime error: unsigned integer overflow: 3600 * 2600730 cannot be represented in type 'unsigned long'
Fix this by make cycles_per_msec a long long.
> gettime: fix cycles_per_msec overflow when using 32 bit longs

- HOWTO
- Sphinx doesn't like non-punctuation characters directly after closing
backticks unless they are escaped so add some backslashes
appropriately.
- Markup /proc/sys/kernel/shmmax in --max-jobs like other /proc/
references.
> doc: minor formatting fixes

- stat.c
Does what it says on the tin. It's pretty much too late to fix the JSON `bw` to be in bytes (see https://github.com/axboe/fio/issues/378#issuecomment-306380285 ) so add a `bw_bytes`  key to help the attentive.
Fixes: https://github.com/axboe/fio/issues/422
> stat: add bw_bytes JSON key

- Makefile
It seems that we need to change the order of linked libraries to make it work by using gcc.
> Makefile: tiny fix of libhdfs

- HOWTO
- fio.1
- Fix up some broken formatting introduced with 074f08170af15ca8ebd469c3a1fa09c38f29904e ("doc: rewrite write_*_log sections")
- Reword buffer_compress_percentage, buffer_compress_chunk and dedupe_percentage sections.
> Minor cleanup and documentation tweaks

- eta.c
Fix up the buffer overflow in ETA output with large numbers of jobs and allow output truncation to happen correctly. Technically this works around the problem in https://github.com/axboe/fio/issues/500 so perhaps the `output` should also be made bigger so the full output is visible...
> eta: fix buffer overflow in ETA output

- engines/mmap.c
verify_only was opening the file with O_RDONLY and the mmap
engine was trying to mmap it with PROT_READ | PROTWRITE hence
getting -EACCESS and failing the job
> fix verify_only when using ioengine=mmap

- eta.c
A bunch of commits around the eta display that
* Fix various off-by-one errors
* Skip the clearing the stale parts of a line when we are starting a new line anyway
* A change how we work out how much of a line is stale
* An increase of the output buffer (as requested in https://github.com/axboe/fio/issues/500#issuecomment-353374981 )
The new stale line clearing is inexact - if the eta line had a newline and then printed 40 characters and the current eta line just prints 40 characters then we will end up thinking we need to clear one character. If you think that is necessary it could be fixed by introducing a variable to track where the "true" start of the line is within the buffer.
> Eta display fixes

- mutex.c
When the commit 8b6a404cdd2c40715885e562416c3db039912773 changed
timeval to timespec, it accsidentally picked timeout time `t' instead
of the current `base' time for checking timewait() really timed out.
t is base + msecs as follows:
base = gettimeofday()
t = base + msecs
pthread_cond_timedwait()
while (!done)
if (timedout)
if (mutex_timed_out(t, msecs))
done = true
Thus, after a good timedout, it burns the cpu for the given msecs
seconds doing tight loop in the while shown above.  This causes 30 to
40 % CPU load on my i5-3360M 2.80GHz while fio server is running.
> mutex: down_timeout: check against the base time

- init.c
- stat.c
First fix address total latency percentiles being 0 when only completion latency is disabled.
The second disables percentile gathering when the corresponding latency option has been disabled. This later change might be more contentious as it might make some outputs (e.g. percentiles with JSON) no longer appear to be present when using conflicting options...
> Percentile fixes

- io_u.c
The case of zonerange < zonesize scenario was not handled
correctly earlier. When zonesize > zonerange, IO must continue
in the same zonerange of the size zonesize for seq-io.
For random io, zonesize > zonerange leads to sequential io
after first zonerange size of io is done when 'norandommap'
is not set. In this case, map needs to be reset for every
zonerange size of IO on a zone.
> Fix zoning issue with seq-io and randommap issue

- filesetup.c
Since commit 0bcf41cdc22dfee6b3f3b2ba9a533b4b103c70c2 ("io_u:
re-invalidate cache when looping around without file open/close") the
job:
./fio --ioengine=null --size=4k --bs=4k --rate=4k \
--time_based --runtime=2s --name=badinvalidate
repeatedly produces the following warning while running:
fio: cache invalidation of badinvalidate.0.0 failed: Bad file descriptor
Fix this by skipping cache invalidation and logging a debug message for
diskless ioengines that don't define an explicit invalidation op.
> filesetup: skip fallback invalidation with diskless ioengines

- client.c
- gclient.c
- io_u.c
- iolog.c
- iolog.h
- server.c
- server.h
- stat.c
- stat.h
Change sizes of counters incremented on each I/O operation from 32-bit to 64-bit. It allows to avoid overflow during several hours test of NVMe devices.
That's related to issue https://github.com/axboe/fio/issues/545
> Fix counter overflow

- diskutil.c
The main commit builds on the work of @bharatpotnuri in https://github.com/axboe/fio/pull/526. As the the main NVMe disk doesn't record any stats when NVMe multipath is in use and virtual NVMe slave devices aren't real block devices it is necessary to try a different sysfs path when the usual one fails.
The second commit just changes some spacing and remove a dot in logging.
> Fix Linux NVMe disk stats

- appveyor.yml
- configure
* If the user is specifying `--disable-optimizations` turn off `march=native` setting too because the chances are they aren't interested. This should keep some distros that already specify `--disable-optimizations` when building their fio packages from getting surprised...
* Disable `march=native` setting in AppVeyor builds. While this technically means we aren't running with the same defaults users get out of the box it's safer to prevent the downloadable MSI binaries from gaining instructions that might be specific to the cloud build host. I suppose if we care enough we can introduce a "native" CI build too but it doesn't seem worth it for now.
> Disable march optimisations in a couple of scenarios

- configure
- iolog.c
- iolog.h
- lib/rbtree.c
- lib/rbtree.h
- parse.c
- stat.c
- t/dedupe.c
- verify.c
To verify whether or not my Linux-specific changes did not cause any portability problems, I tried to build fio on a NetBSD system. The patches in this series make it possible to build fio on NetBSD. The only verification I have done of these changes is to verify that "make test" passes on both Linux and NetBSD.
> Make it possible to build fio on NetBSD

- Makefile
- configure
- log.c
- oslib/asprintf.c
- oslib/asprintf.h
- verify.c
Since I would like to use the asprintf() function in the ZBC code and since that function is not available on every platform supported by fio, add an asprintf() implementation. Use asprintf() where appropriate.
> Add an asprintf() implementation

- backend.c
The two patches in this pull request do not change the behavior of switch_ioscheduler() but make this function easier to analyze for static analyzers like Coverity.
> Make switch_ioscheduler() easier to analyze

- arch/arch-aarch64.h
- configure
- crc/crc32c-arm64.c
- crc/crc32c-intel.c
- crc/crc32c.h
- os/os-linux.h
- os/os.h
It turns out FreeBSD 12 has added a `sys/auxv.h` header but does not implement `getauxval()` (they have added a slightly incompatible alternative called `elf_aux_info()`) causing issues so the first commit makes the configure test more robust by checking we also have `getauxval()` (but only on Linux) and erroring in other cases. Also move Linux specific runtime check into `os/os.h` and reduce some defines.
(I've a follow on commit in https://github.com/sitsofe/fio/tree/aarch64-crc32c-freebsd that adds runtime CRC32c detection for FreeBSD/arm64 it but FreeBSD haven't gotten around to hooking up the code in their kernel that fills out `AT_HWCAP2` on aarch64 so my commit couldn't be tested in the case where the feature should be detected successfully at runtime...)
The second commit here …
> Aarch64 crc32c + minor style fixes

- parse.c
Ensure that floating point option ranges are properly formatted if
only one of the two boundaries is specified. A few examples of how
option ranges are formatted with this patch applied:
range: max=100.000000
range: min=0.000000, max=100.000000
range: min=0.000000
Reported-by: Sitsofe Wheeler <sitsofe@gmail.com>
Signed-off-by: Bart Van Assche <bart.vanassche@wdc.com>
> Fix floating point option range formatting

- HOWTO
- configure
- engines/libpmem.c
- engines/pmemblk.c
- fio.1
- options.c
The NVML library was renamed to PMDK (Persistent Memory Development Kit).  Project homepage can be found at http://pmem.io/pmdk/.  The PMDK code is hosted at https://github.com/pmem/pmdk/.  A blog entry announcing the change can be found here: http://pmem.io/2017/12/11/NVML-is-now-PMDK.html.
> NVML renamed to PMDK

- HOWTO
- engines/sg.c
- fio.1
Jens, please consider this pull request that adds to the sg ioengine support for the WRITE AND VERIFY and WRITE SAME commands. We have collected bus traces and the commands are working as expected.
> Add support for WRITE AND VERIFY and WRITE SAME to the sg ioengine

- diskutil.c
- fio.h
- nowarn_snprintf.h
- verify-state.h
Introduce a new function nowarn_snprintf() that behaves identically
to snprintf() except that it does not make gcc complain about potential
truncation of the output buffer.
Signed-off-by: Bart Van Assche <bart.vanassche@wdc.com>
> Suppress gcc 8 compiler warnings

- lib/nowarn_snprintf.h
This patch suppresses the following Coverity complaint:
CID 175867:  API usage errors  (VARARGS)
va_end was not called for "args".
> Make nowarn_snprintf() call va_end()

- HOWTO
- filesetup.c
- fio.1
- fio.h
- init.c
- options.c
- t/jobs/readonly-r.fio
- t/jobs/readonly-t.fio
- t/jobs/readonly-w.fio
- t/readonly.sh
Jens, please consider these patches related to trim workloads and the readonly option. fio currently allows destructive trim workloads when the readonly option is enabled. These patches put write and trim workloads on equal footing with respect to the readonly option.
> trim and readonly option

- engines/gfapi.h
- engines/glusterfs.c
Current multi-thread test creates one glfs instance per job. However,
there is requirement to run all jobs on one single instance, and that
all jobs would share the same set of underlying working threads.
Add a new option "single-instance" to control whether to create one
global instance or one instance per job. For testing with mutilple
gluster volumes, use host name and volume name to filter out same
volume, one specific volume will have one instance.
> capable to test glusterfs with one single glfs instance

- HOWTO
- fio.1
In both the norandommap option section, and the verify option section,
add text warning that norandommap can cause data verification errors
when using async io engines and io depths > 1.
Signed-off-by: Steve Wise <swise@opengridcomputing.com>
> doc: add text about possibly verify errors with norandommap

- HOWTO
- engines/libaio.c
- engines/sg.c
- fio.1
- ioengines.c
- stat.c
- t/sgunmap-perf.py
- t/sgunmap-test.py
This is a follow-up to #590 
Jens, please consider this pull request.
These patches add trim support to the sg ioengine via the SCSI unmap command. Following the established sg pattern, unmap commands for block devices are carried out synchronously. For character devices, however, it is possible to submit multiple ranges with a single unmap command by setting iodepth_batch.
@sitsofe, I considered adding an option to use WRITE SAME but using unmap was my first priority since that was what was requested by the group that this feature was developed for. Note that it would be pretty easy to add an option so that write workloads with sg_write_mode=same carry out trims.
> Add trim support to the sg ioengine

- iolog.c
- os/os-windows.h
Checks is file provided via --read_iolog parameter is a unix socket.
In such case connect to it and fetch data from there.
> iolog: allow to read_iolog from unix socket

- HOWTO
- backend.c
- fio.1
- fio.h
- iolog.c
- options.c
- thread_options.h
Used to avoid reading large iologs at once.
Allows iologs to be infinite, generated.
> iolog: Added option read_iolog_chunked. 

- backend.c
- filesetup.c
- ioengines.c
- iolog.c
- iolog.h
When iolog is read in chunked mode, some prefetching is done. Based on this size of buffers are determined.
Further operations may need larger buffers. If so, io_u buffers are reallocated.
Example that cause problem when read_iolog_chunked=1:
fio version 2 iolog
rbd_data.0 add
rbd_data.0 open
rbd_data.0 write 0 4096 (x20)
rbd_data.0 write 0 4096000 (x10)
rbd_data.0 close
> Realloc io_u buffers to adapt to operation size.

- arch/arch-arm.h
The FreeBSD folks found fio didn't build on their armv6 systems
(https://svnweb.freebsd.org/ports/head/benchmarks/fio/Makefile?revision=432897&view=markup
) but Mikaël Urankar fixed the issue in
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228042 so copy the fix
to mainline.
> arch: fix build breakage on armv6

- HOWTO
- fio.1
Improve the documentation of the zonesize, zoneskip and zonerange job
options such that this documentation becomes easier to comprehend.
Signed-off-by: Bart Van Assche <bart.vanassche@wdc.com>
> Improve zone support documentation

- lib/axmap.c
- t/axmap.c
New algorithm starts the search at the specified bit, and only
looks forward (higher index) for a free bit, wrapping around the
end of the map if necessary.  This avoids a distribution skew in
the current algorithm where the low order 5 or 6 bits of the
replacement address tend toward zero.
The first_free cached value is not updated or used. But performance
of the new algorithm is marginally faster than the old algorithm
when measured on a 200 million entry map that is half full,
averaged across searches starting with each of the 200 million
entries.
A separate commit adds new tests to t/axmap.c to confirm the
correct behavior in a variety of situations and edge cases.
> Reimplement axmap_next_free() to prevent distribution skew

- HOWTO
- Makefile
- configure
- engines/ime.c
- examples/ime.fio
- options.c
This PR aims at bringing support for DDN’s Infinite Memory Engine (IME) in FIO.
To that end, 3 engines were created to test the different functions provided by IME. These are called ime_psync, ime_psyncv, and ime_aio. You can find these engines in engines/ime.c.
Could you have a look and tell us if this patch can be merged ?
If you want to compile and run some tests, we can provide a wrapper library to mock IME function calls using POSIX calls.
Signed-off-by: Gaëtan Bossu <gbossu@ddn.com>
> engines: Add support for DDN's Infinite Memory Engine

- lib/axmap.c
- lib/axmap.h
With the new axmap_next_free() implementation, the "first_free" cache
is no longer used.  Remove all references to it.  Also axmap_clear()
is never referenced, so remove it and related code.
> Remove unused code in lib/axmap.c

- fio.1
- iolog.c
- options.c
- options.h
Useful when --numjobs is more then 1. Each job gets subsequent iolog to process.
> iolog: Now --read_iolog can contain multiple replay files, separated by ':'.

- init.c
This is a gist of the problem. According to documentation, if no job name is given, resulting name of the log should be: `jobname_type.x.log`. However, it is unspecified what happens when config file has for instance:
```
write_lat_log=
write_bw_log=
write_iops_log=
```
... as opposed to ...
```
write_lat_log
write_bw_log
write_iops_log
```
What ends-up happening, if the former is used in the config file are names of logs which start with `_`, and look like `_iops.log`, or `_bw.log`, etc.
While one might argue that it is not reasonable to expect that names will be correct if the value is in effect an empty string, in my mind this should be accounted for and jobname string used instead, just like what would happen if there was no `=some value`. Correctness of this change is debatable, but …
> Log files names start with _ when write_XX_log= keys in config file have empty value(s)

- zbd.c
- zbd.h
Two patches: the first one improves randomness of reads for a random read pattern with read_beyond_wp=0 by adjusting an I/O offset to a random value within the zone with valid data chosen. The second patch removes declaration for dead code.
> ZBD support improvement and cleanup

- tools/hist/fio-histo-log-pctiles.py
this dependency on unittest2 module was causing heartburn for pbench community so I removed the dependency.  If python-unittest2 package is installed and unittest2 module can be imported, that's fine, we'll use it if requested, but if it's not, that's fine too, you can still use the program.
> remove dependency on unittest2 module

- rate-submit.c
Jens, please consider this pull request.
Another way to resolve this issue would be to set td = td->parent before calculating needs_lock in put_io_u(). If that is better, I can submit a patch for that change instead.
> rate_submit: synchronize accesses to io_u_queue->nr

- tools/hist/fio-histo-log-pctiles.py
This is a workaround for bug in fio-3.3. It causes this to happen:
```
$ python ~/ceph/fio/fork/fio/tools/hist/fio-histo-log-pctiles.py ~/tmp/fio_clat_hist.1.log 
Traceback (most recent call last):
File "/home/bengland/ceph/fio/fork/fio/tools/hist/fio-histo-log-pctiles.py", line 656, in <module>
compute_percentiles_from_logs()
File "/home/bengland/ceph/fio/fork/fio/tools/hist/fio-histo-log-pctiles.py", line 390, in compute_percentiles_from_logs
max_timestamp_all_logs)
File "/home/bengland/ceph/fio/fork/fio/tools/hist/fio-histo-log-pctiles.py", line 206, in align_histo_log
weight /= (time_msec_end - time_msec)
ZeroDivisionError: float division by zero
```
Here is the log file [fio_clat_hist.1.log](https://github.com/axboe/fio/files/2376204/fio_clat_hist.1.log), column 1 of the first 4 …
> filter out records with duplicate timestamps

- Makefile
- configure
The Makefile forced static Windows builds by adding -static to the
CFLAGS but this is long after the configure tests had run. This could
lead to problems (such as https://github.com/axboe/fio/issues/683 "Fio
fails to link libcurl on windows (undefined references to
__imp_curl_easy_cleanup)") where the availability of a dynamic version
of library causes a feature to be enabled but when it comes to final
linking time we find that there's no static version of the library
available and fall over.
Fix the above by asking for a static build via the "Forcing some known
good options on Windows" section of the configure file which occurs
prior to configure tests. This also means configure will correctly
display that we are doing a static build.
Fixes https://github.com/axboe/fio/issues/683 …
> build: change where we set -static for Windows

- zbd.c
Instead of returning sizeof(struct fio_zone_info) * (zone number),
return the zone number.
> zbd: Fix zbd_zone_nr()

- fio.h
`MPOL_LOCAL` will be defined in `numaif.h` in the future.
Also, `MPOL_MAX` will be changed to match the kernel values.
> Check if `MPOL_LOCAL` declared before defining

- HOWTO
- backend.c
- fio.1
- fio.h
- init.c
- ioengines.c
- rate-submit.c
Jens, please consider this follow-up to #700 
We used blktrace to collect data from runs with 4K r/w jobs combined with a 1G trim and found no overlapping IOs submitted.
Here are responses to your earlier comments and changes from the previous version:
- moved overlap check from main job thread to submit worker threads
- use original serialize_overlap check function to compare each io_u with io_u_all queues for each running thread of interest
- moved init changes to a separate patch
- there needs to be a single overlap check mutex for all threads (instead of one per workqueue) to prevent two threads with overlapping IOs from finding that the coast is clear and submitting IOs that overlap
- I could not think of a way to avoid iterating over threads. I could create an array of *io_u_queue …
> Enable --serialize-overlap when --io_submit_mode=offload

- filesetup.c
> iolog: Fix problem with setup() not invoked when read_iolog is used.

- arch/arch-arm.h
6K was missing from the defines.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> arch: fix build breakage on armv6 again

- filesetup.c
- fio.h
- init.c
- lib/lfsr.c
- lib/lfsr.h
- lib/rand.c
- lib/rand.h
- os/os-windows.h
- os/os.h
- verify.c
- verify.h
The long data type is 32-bit on LLP64 platforms
> rand: fix truncated rand_seed on Windows

- engines/io_uring.c
When reaping some completed I/O before io_uring_enter(), it waits forever.
Signed-off-by: Satoru Takeuchi <sat@cybozu.co.jp>
> io_uring: fix possible infinite loop

- configure
librbd will run up to 20% faster under small IO workloads when fio is linked
against tcmalloc. By automatically linking against tcmalloc, it avoids
the need to use LD_PRELOAD to pull in a faster memory management toolset.
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
> configure: attempt to link against tcmalloc by default if available

- fio.1
- init.c
- parse.h
Per issue #794, double the maximum length of a line in a fio job file to 8192 bytes. This changes the hard-coded malloc and fgets in init.c to use OPT_LEN_MAX instead of 4096 and increases OPT_LEN_MAX to 8192. I've also documented the maximum length of a line in the man page, since 8192 is a somewhat arbitrary increase and someone may need it increased further later on.
> Increase maximum length of line in jobs file to 8192

- engines/libiscsi.c
Signed-off-by: Kyle Zhang <kyle@smartx.com>
> libiscsi: log reason of error when readcapacity failed

- engines/libiscsi.c
When poll meets EINTR, it should continue working rather than return
error.
Signed-off-by: Kyle Zhang <kyle@smartx.com>
> libiscsi: continue working when meets EINTR or EAGAIN

- smalloc.c
- smalloc.h
- t/stest.c
More and longer jobs in client/server mode with --status-interval=1 increase shared memory usage and may trigger an erroneous smalloc OOM error.
@axboe, please consider the patches in this pull request to resolve the issue.
The patches include a modification of t/stest.c to expose the problem and a fix for the problem.
> smalloc garbage collection

- engines/io_uring.c
Without this change SQEs can contain data set in previous
submissions. E.g. a WRITE following an fdatasync would have still have
IORING_FSYNC_DATASYNC set in sync_flags, which shares storage with the
WRITE's rw_flags. Which was not reset, causing all writes to be
synchronous. Similarly, an fsync following a READ/WRITE would not
reset off/addr/len, which causes errors, because the kernel's
io_prep_fsync returns an error if e.g. addr is not 0.
While this could also be fixed by resetting only the unused fields in
the respective branches, it seems less failure prone to start with a
zeroed out sqe.
> engines/io_uring: Fully clear out previous SQE contents.

- gclient.c
Commit 36833fb04 replaced many usages of strncpy with snprintf.
But there is one place where new arguments were added but the function
name has not been changed. It leads to the following compilation error:
gclient.c:333:2: error: too many arguments to function ‘strncpy’
333 |  strncpy(message, sizeof(message), "%s", status_message);
|  ^~~~~~~
In file included from /usr/include/features.h:450,
from /usr/include/bits/libc-header-start.h:33,
from /usr/include/stdlib.h:25,
from gclient.c:1:
/usr/include/bits/string_fortified.h:103:1: note: declared here
103 | __NTH (strncpy (char *__restrict __dest, const char *__restrict __src,
| ^~~~~
Signed-off-by: Anatol Pomozov <anatol.pomozov@gmail.com>
> Fix compilation error with gfio

- HOWTO
- configure
- fio.1
- os/os-mac.h
Change configure compile probes to fail on implicit declarations. This
(correctly) stops us from enabling fdatasync on OSX which was
problematic because we were actually calling a syscall stub with
arguments different to what was declared in its prototype (see
https://github.com/gbrault/picoc/issues/145#issuecomment-89734655 and
https://gitlab.freedesktop.org/xdg/shared-mime-info/issues/7 ).
Fixes: https://github.com/axboe/fio/issues/834 ("Drop macOS support for
fdatasync")
@axboe This patch is simplistic and basically adds erroring on `implicit-function-declaration` warnings to the two probe compilation functions. It might be better to just error on all warnings during compilation probes (if so let me know and I'll recreate the patch). I …
> configure: stop enabling fdatasync on OSX

- blktrace.c
A fix for handling blktraces containing trims.  Please see github issue: https://github.com/axboe/fio/issues/771
Thanks
> fix trim blktrace replay

- filelock.c
When running hundreds of threads and collecting CLAT, SLAT, IOS on a
per-thread basis, FIO can need a lot of file locks to complete.  When
it can't get them, it gives the cryptic error message:
> fio: filelock.c:182: __fio_lock_file: Assertion `!trylock' failed.
Bump the maximum from 128 to 1024 to give headroom for high core count,
high thread count testing.
> Increase MAX_FILELOCKS for highly parallel IO test

- stat.c
Commit 6cc0e5aa9eddd2487dfa9ac80be1264151058409 ("Fix overflow of
counters incremented on each I/O operation") changed various structures
from [unsigned] int -> [u]int64_t but the size used when memcpy-ing
histogram data was still the older (smaller) size. This led to un-copied
values and usage of uninitialised data. An example job that demonstrates
the issue is:
$ valgrind ./fio --size=256k --thread=1 --rate_iops=5 --direct=1 \
--number_ios=15 --name=hist_test --filename=fio.test \
--log_hist_msec=1000 --write_hist_log=fio.test --log_hist_coarseness=6
==1743== Memcheck, a memory error detector
[...]
fio-3.16-8-gf951
Starting 1 thread
==1743== Thread 3: IOPS: [R(1)][23.1%][r=20KiB/s][r=5 IOPS][eta 00m:10s]
==1743== Use of uninitialised value of size 8
==1743==    at 0x609D86B: _itoa_word …
> stat: fix corruption in histogram logs

- Makefile
Android replaces syslog calls with calls to the Android system logging library, `liblog`. Link to `liblog` when compiling for Android to fix the following undefined reference errors:
```
aarch64-linux-android-ld: log.o: in function `android_polyfill_vsyslog':
/usr/include/syslog.h:185: undefined reference to `__android_log_print'
aarch64-linux-android-ld: /usr/include/syslog.h:182: undefined reference to `__android_log_vprint'
```
> Link to the system logging library on Android

- backend.c
We should not use break, we should use return 1 and explictly fails this,
then the cleanup routine will work. If not, this function may still
return 0.
Signed-off-by: Gang Cao <cao.gang@intel.com>
Signed-off-by: Ziye Yang <ziye.yang@intel.com>
> backend: fix the memory leak if fio_memalign fails,

- backend.c
The previous version used the bashism "&>" to redirect stdout and stderr of the prerun/postrun commands to an output file. Since system() executes the command using "/bin/sh sh -c …". If /bin/sh is not bash, this wont work (for example, Ubuntu uses dash since 6.10).
Use the "posixly-correct" way of redirecting stdout to the output file and then redirect stderr to stdout.
Signed-off-by: Hannes Weisbach <hannes.weisbach@gmail.com>
> backend: Fix output redirection of exec_prerun/_postrun

- parse.c
This might be overkill just to silence the warnings, but having
a common function for const and non-const version makes it discard
const pointer at some point.
```
--
CC parse.o
parse.c: In function 'find_option_c':
parse.c:1051: warning: passing argument 1 of 'find_option' discards qualifiers from pointer target type
parse.c: In function 'get_option':
parse.c:1051: warning: passing argument 1 of 'find_option' discards qualifiers from pointer target type
parse.c:1051: warning: passing argument 1 of 'find_option' discards qualifiers from pointer target type
parse.c: In function 'parse_cmd_option':
parse.c:1051: warning: passing argument 1 of 'find_option' discards qualifiers from pointer target type
```
> parse: Silence discard-const warning on OpenBSD

- HOWTO
- file.h
- filesetup.c
- fio.1
- init.c
- options.c
- os/os.h
Fixes #833. Provides the ability to initially "layout" the file
by ftruncating it to the desired size before performing IO. This
is mainly useful on Windows, which serializes all writes that
extend the size of a file. Using this option with a suitable
iodepth allows fio to emulate the behavior of Windows Explorer
file copy, which always truncates to the expected size before
issuing writes for performance reasons.
> Add fallocate=truncate option.

- engines/rados.c
A thinko has popped in implementation. Consumer function `getevent()` did pick last (newest) instead of first (oldest).
> engines/rados: fix error with getting last instead of first element from list

- .travis.yml
The previous commit that added support for xcode11.2 resolved the
steadystate_tests scipy dependency with 'pip3 install scipy'. However,
the travis xcode11.2 image changed and now we need 'pip install scipy'
to provide the scipy dependency. To forestall future issues, install
scipy for both python2 and python3.
Also enable debug output in run-fio-tests.py to provide more information
in case of failure.
This resolves the Travis-CI problem @sitsofe encountered in https://github.com/axboe/fio/pull/879
> .travis.yml: xcode11.2 scipy issue

- client.c
- server.c
In client/server mode, fsync latencies were missing because a couple
data structures were missed in the client/server send/receive thread
stats code. This patch adds those data structures and now we are able to
see the fsync latencies in client/server mode.
Fixes: https://github.com/axboe/fio/issues/878
Signed-off-by: Vincent Fu <vincent.fu@wdc.com>
> client/server: add missing fsync data structures

- Makefile
Recent Cygwin mingw releases require linking against libssp to avoid
undefined symbols. See
https://github.com/msys2/MINGW-packages/issues/5868 for discussion.
Fixes: https://github.com/axboe/fio/issues/881
> Makefile: add libssp for Windows

- configure
- filesetup.c
- options.c
- os/os-windows.h
- os/os.h
- Fix double directory prefix concatenation that was happening after
95af8dd57a7a9a564f99492bb1e04bb6d13b95b1 ("filesetup: don't call
create_work_dirs() for ioengine with FIO_DISKLESSIO") refactored some
code
- Stop always using '/' and switch to using FIO_OS_PATH_SEPARATOR when
concatenating the directory value to the filename in set_name_idx()
- Change the permissions directories are created with to have the
execute bit so they can be entered(!)
- Fix bug where filenames that were absolute unix paths would prevent
the creation of intermediate directories
- Remove the configure mkdir test and introduce fio_mkdir to hide mkdir
platform differences
- Make Windows mkdir emulation more robust against multiple slashes
after the drive letter and when dealing dealing with with paths
containing …
> filesetup: fix directory creation issues

- io_u.c
When using "rate" with "time_based", the amount of time to sleep should be based on the invocation time (epoch) rather than the start time of a given loop (start) because no other statistics are reset when a file is re-opened. Prior to this change, a wrap-around would cause the rate_ddir code to compute that ~0 time had elapsed since the last I/O (i.e., a near-infinite rate), and
trigger a very long sleep in an attempt to adjust to the given rate.
It's possible there's a cleaner fix to be made in the get_next_offset code to avoid re-opening the file on wrap-around when file size (accounting for offsets and strides) isn't a perfect multiple of IO size, but I'm having a harder time working through that code, so does this simple accounting approach work for you?
Testing done:
Using …
> io_u: fix rate limiting to handle file wrap-around

- fio.h
- lib/memalign.c
- lib/memalign.h
- t/dedupe.c
- unittests/lib/memalign.c
- unittests/unittest.c
- unittests/unittest.h
`fio_memalign()`/`fio_memfree()` implementation shouldn't depend on
`smalloc()`/`sfree()` which has dependency on fio code itself.
e.g. This forces unittest code to prepare stab functions for `smalloc()`/`sfree()`.
This `smalloc()`/`sfree()` dependency was added by 3114b675fd
("fio: enable cross-thread overlap checking with processes").
Rename `fio_memalign()`/`fio_memfree()` to `__fio_memalign()`/`__fio_memfree()`
and take a function pointer instead of a boolean flag.
Add `fio_memalign()`/`fio_memfree()` as an inlined wrapper for
`__fio_memalign()`/`__fio_memfree()` without API change.
The only real change here is `lib/memalign` functions got renamed.
Signed-off-by: Tomohiro Kusumi <kusumi.tomohiro@gmail.com>
> lib/memalign: remove smalloc()/sfree() dependency

- json.c
Signed-off-by: Tomohiro Kusumi <kusumi.tomohiro@gmail.com>
> json: remove two redundant json_print_array() prototypes

- .appveyor.yml
- t/run-fio-tests.py
- t/steadystate_tests.py
Jens, please consider these two patches. They make small improvements to the automated test infrastructure:
- automatically skip one test that does not run on Windows
- avoid spurious failures by relaxing acceptance criteria in steadystate_tests
> testing patches

- verify.c
io->numberio can not be populated when verify_only is true, because
do_dry_run() build and complete IOs immediately, so it can not replicate
the numberio that was produced when the data was layered on the media.
Without this fix, using write_random
[write_stress]
filename=${FILENAME}
size=${FILESIZE}
verify_only=${VERIFY_ONLY}
readwrite=randwrite
bs=4k
ioengine=libaio
iodepth=32
direct=1
do_verify=1
verify=crc32c
'VERIFY_ONLY=1 FILENAME=/dev/sda1 FILESIZE=1M fio write_random' passes,
but
'VERIFY_ONLY=0 FILENAME=/dev/sda1 FILESIZE=1M fio write_random' fails:
"""verify_only option fails with verify: bad header numberio 1, wanted
0""".
The fix addresses the problem by not checking numberio.
Fixes #732
Signed-off-by: Gwendal Grignou <gwendal@chromium.org>
> verify: Fix test to not check for numberio when verify_only is true

- HOWTO
- client.c
- engines/filecreate.c
- engines/filestat.c
- engines/io_uring.c
- engines/libaio.c
- eta.c
- fio.1
- fio.h
- init.c
- io_u.c
- io_u.h
- ioengines.c
- iolog.c
- iolog.h
- server.c
- server.h
- stat.c
- stat.h
This adds the libaio option prio_percent which allows a certain percentage of commands to be sent at a higher priority. Since this only is relevant to reads on the drive side, only reads will be broken down into multiple priorities like this. The latencies of the two priority types will be reported separately in addition to the combined latencies. This will only affect normal and json reporting.
> Adding libaio/io_uring option cmdprio_percentage

- HOWTO
- engines/filestat.c
- fio.1
- optgroup.h
Use `stat(2)` by default, but `lstat(2)` if "lstat" bool option specified.
> engines/filestat: add "lstat" option to use lstat(2)

- os/os-openbsd.h
OpenBSD uses swap16/32/64, not bswap16/32/64:
https://man.openbsd.org/swap32
On OpenBSD architectures that still use gcc this results in compilation warnings and linking errors:
```
cc -o crc/sha3.o -std=gnu99 -Wwrite-strings -Wall -Wdeclaration-after-statement -g -ffast-math -O2 -pipe   -D_GNU_SOURCE -include config-host.h -I. -I/usr/obj/ports/fio-3.17/fio-fio-3.17 -DBITS_PER_LONG=64 -DFIO_VERSION='"fio-3.17"' -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DFIO_INTERNAL -DFIO_INC_DEBUG -c /usr/obj/ports/fio-3.17/fio-fio-3.17/crc/sha3.c
/usr/obj/ports/fio-3.17/fio-fio-3.17/crc/sha3.c: In function 'fio_sha3_final':
/usr/obj/ports/fio-3.17/fio-fio-3.17/crc/sha3.c:169: warning: implicit declaration of function 'bswap64'
...
/usr/ports/pobj/fio-3.17/fio-fio-3.17/crc/sha3.c:169: undefined …
```
> Use swap16/32/64 on OpenBSD.

- gettime.c
OpenBSD sparc64 doesn't have __thread support and there's no cpu clock support in fio for sparc64 which results in the following compilation error:
```
cc -o gettime.o -std=gnu99 -Wwrite-strings -Wall -Wdeclaration-after-statement -g -ffast-math -O2 -pipe   -D_GNU_SOURCE -include config-host.h -I. -I/usr/obj/ports/fio-3.17/fio-fio-3.17 -DBITS_PER_LONG=64 -DFIO_VERSION='"fio-3.17"' -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DFIO_INTERNAL -DFIO_INC_DEBUG -c /usr/obj/ports/fio-3.17/fio-fio-3.17/gettime.c
/usr/obj/ports/fio-3.17/fio-fio-3.17/gettime.c: In function 'fio_local_clock_init':
/usr/obj/ports/fio-3.17/fio-fio-3.17/gettime.c:380: error: 'tv_tls_key' undeclared (first use in this function)
/usr/obj/ports/fio-3.17/fio-fio-3.17/gettime.c:380: error: (Each undeclared identifier is …
```
> Fix build on architectures that don't have both cpu clock and __thread support.

- stat.c
It is obvious on many runs that bw and iops averages from statistics based
on samples are way off (sometimes by an order of magnitude) in comparison
to the main numbers reported for these values.
When sampling these values fio assumes that their each next averaging
interval starts exactly the set averaging interval later from the start of
the previous averaging interval.
However, this isn't necessary true as scheduling delays may lengthen such
intervals, so the next one should start when the previous one has actually
ended, since that's when the collected totals are counted.
On my test system (with fio set to the default averaging interval length of
500 msec) the actual lengths are usually around 650 msec, however
700+ msec intervals aren't unusual.
This causes pretty significant bw and …
> stat: fix calculation of bw and iops statistics based on samples

- HOWTO
- engines/filestat.c
- fio.1
Per suggestion from Jens, change a bool option to str option
to better support `stat(2)` variants (at this point before 3.18).
https://github.com/axboe/fio/pull/912#issuecomment-577814885
> engines/filestat: change "lstat" bool option to "stat_type" str option

- HOWTO
- cconv.c
- client.c
- fio.1
- gclient.c
- init.c
- options.c
- server.c
- server.h
- stat.c
- stat.h
- t/latency_percentiles.py
- t/run-fio-tests.py
- thread_options.h
This pull request adds the ability to report percentiles for submission, completion, and total latency. Previously, fio could report percentiles for only one of completion or total latency. With these patches fio will be able to report percentiles for all three latency types. A python test script for this new feature is also included.
Other notes:
- small fixes related to cmdprio_percentage
-- bugfix with unified_rw_reporting
-- in stat.c:add_ddir_status_json() do not consider reporting cmdprio_percentage latencies for ddir=fdatasync
-- make cmdprio_percentage min/max/mean/stddev statistics and percentiles both describe total latency when lat_percentiles=1
- latency_percentiles.py takes about 3 minutes to complete when run on an SSD. It computes percentiles from --write_lat_log output and …
> Report percentiles for submission, completion, total latency

- json.c
- json.h
- stat.c
Coverity reports the following false positive for the JSON code in stat.c:
CID 284826 (#1 of 1): Resource leak (RESOURCE_LEAK)
17. leaked_storage: Variable percentile_object going out of scope leaks the storage it points to.
Suppress this false positive by making the JSON code easier to analyze. The
changes in this patch are as follows:
- Change the macros in json.h into inline functions such that the compiler
performs argument type verification at compile time.
- Pass a struct json_value pointer to json_*_add_value_type() instead of
using varargs.
> Make the JSON code easier to analyze

- t/latency_percentiles.py
There was a division by zero error which led to a false failure report in an [AppVeyor run](https://ci.appveyor.com/project/axboe/fio/builds/30996510/job/osc8qdqhl6jmx03h) for https://github.com/axboe/fio/pull/932. This patch eliminates the possibility of the division by zero.
> avoid division by zero in t/latency_percentiles.py

- tools/genfio
Not all distros have done usrmerge - Debian
https://salsa.debian.org/debian/fio/-/blob/5a608e04b947aed0d3b49d7ca9a85ed9afe9ec56/debian/patches/genfio-interpreter
and SUSE (https://build.opensuse.org/request/show/541207 ) have been
carrying a patch changing the interpreter for genfio back to /bin/bash
and that's before you get to other OSes such as macOS...
Since /bin/bash works everywhere let's do this upstream too.
Fixes: https://github.com/axboe/fio/pull/883
Inspired-by: Changcheng Liu <changcheng.liu@aliyun.com>
> genfio: use /bin/bash hashbang

- Makefile
`rm -f $(T_PROGS) $(T_TEST_PROGS)` in `clean` target is intended to
remove all binaries under t directory, but it actually fails to remove
`t/{fio-btrace2fio,io_uring,read-to-pipe-async}` files for not
evaluating platform specific variables on `make clean`.
```
5.4.17-200.fc31.x86_64
t/fio-btrace2fio: ELF 64-bit LSB executable,
t/io_uring: ELF 64-bit LSB executable,
t/read-to-pipe-async: ELF 64-bit LSB executable,
```
The easiest way to fix this is to hard-code these conditionally
compiled binaries.
> Makefile: don't fail to remove conditionally compiled binaries on clean

- filesetup.c
- os/os-windows.h
The commit df18600fd06258b96ae6f6b530ecdff541c2a82d ("filesetup: fix
directory creation issues") broke Windows raw/physical disk access
because Windows doesn't consider a path that only consists of a
namespace (such as the device namespace "\\.\" - see
https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#namespaces
for information on Windows' namespaces) to exist as a directory(!).
Workaround the issue for raw devices by explicitly considering the
device namespace subcomponent to always be valid. Further, intermediate
path components in UNC paths or paths starting with a namespace might
also not "exist" so introduce backwards scanning for the longest
pre-existing directory to sidestep this. The function doing this is made
available for non-windows …
> filesetup: fix win raw disk access and improve dir creation failure msg

- Makefile
- configure
- engines/filestat.c
- oslib/statx.c
- oslib/statx.h
This commit
1) tests existence of `statx(2)` and libc support on `./confiugre`.
2) adds `oslib/statx.c` and implements `statx(2)` using above result.
3) adds `statx(2)` support in filestat ioengine.
Confirmed compilation on Fedora31, FreeBSD, and NetBSD.
> engines/filestat: add statx(2) syscall support

- configure
It errors when passing NULL or 0. Passing an empty va_list works.
> configure: fix vasprintf check under musl

- .appveyor.yml
- .travis.yml
- t/jsonplus2csv_test.py
- t/run-fio-tests.py
- tools/fio_jsonplus_clat2csv
Jens, please consider this series of patches that updates tools/fio_jsonplus_clat2csv to support the multiple submission/completion/total latency percentiles feature added in fio 3.18.
fio_jsonplus_clat2csv is now able to properly process any slat/clat/tlat counts that are produced. However, this breaks backward compatibility as the CSV format is changed.
Also add a test for this script and incorporate it with the automated testing suite.
The final patch resolves a problem introduced by a change to the travis-ci xcode 11.2 image (https://travis-ci.com/github/vincentkfu/fio/jobs/302726308)
> Update tools/fio_jsonplus_clat2csv for multiple submission/completion/total latency percentiles

- stat.c
b2a432bfbb6d inadvertently added extra log samples.
$ ./fio-canonical/fio --name=test --time_based --runtime=10s --write_lat_log=fio-07-b2a432 --log_avg_msec=1000 --size=1G --rw=rw
test: (g=0): rw=rw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.17-93-gb2a4
Starting 1 process
...
$ cat fio-07-b2a432_clat.1.log
1000, 5851, 0, 0, 0
1000, 2551, 1, 0, 0
1000, 5028, 1, 0, 0
2000, 4175, 0, 0, 0
2000, 3214, 1, 0, 0
2000, 60619, 0, 0, 0
...
There should only be two lines at each timestamp (one for reads, one for
writes), but the first two timestamps have three lines each.
The cause is an inadvertent change in stat.c:add_log_sample() of
__add_stat_to_log to _add_stat_to_log. Reverting to the two-underscore
version resolves this issue.
Fixes: …
> stat: eliminate extra log samples

- Makefile
- configure
It is a usual practice to build sw by passing `CFLAGS="-foo"` on
configure stage. It didn't work with FIO though. This commit fixes two
problems:
* configure: this script was overriding user CFLAGS
* Makefile: this script was appending its own CFLAGS instead of
prepending them. The problem with this one is that it sets a -O3
option, but a user may have wanted to disable optimization, so they set
-O0 option. And by appending our CFLAGS we make user CFLAGS to not work.
> configure/Makefile: don't override user CFLAGS

- .appveyor.yml
For debugging test failures, package test artifacts and make them
available for download. Exclude certain files to reduce size of the
compressed archive.
Suggested-by: Sitsofe Wheeler <sitsofe@gmail.com>
Signed-off-by: Vincent Fu <vincent.fu@wdc.com>
> appveyor: make test artifacts available for inspection

- json.h
eb2f29b7fd("Make the JSON code easier to analyze") doesn't compile
on RHEL6 using gcc4.x.
Using `{.object = val,},` for an union field seems to fix the issue,
but just use `arg.object = val;` instead as this is guaranteed to
compile on supported platforms.
```
CC gettime.o
In file included from stat.h:7,
from thread_options.h:7,
from fio.h:18,
from gettime.c:7:
json.h: In function 'json_object_add_value_object':
json.h:95: error: unknown field 'object' specified in initializer
json.h:95: warning: missing braces around initializer
json.h:95: warning: (near initialization for 'arg.<anonymous>')
json.h:95: warning: initialization makes integer from pointer without a cast
make: *** [gettime.o] Error 1
```
> json: Fix compile error on RHEL6

- helper_thread.c
- stat.c
Jens, please consider these changes.
We observed inconsistent status intervals after the signal handler safety changes to the helper thread. Changing the select() timeout did not resolve the issue. Moving the status-interval trigger from the main fio thread to the helper thread did the trick, however.
> Fix inconsistent status-interval intervals

- helper_thread.c
On Windows, the ETA is not updated after ramp_time expires. For example:
```
C:\fio-dev>fio\fio --name=test --runtime=5s --time_based --ramp_time=5 --size=1M --ioengine=null --thread
test: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=null, iodepth=1
fio-3.19-54-g9bc8
Starting 1 thread
Jobs: 1 (f=0): [/(1)][-.-%][eta 00m:05s]
test: (groupid=0, jobs=1): err= 0: pid=5344: Tue May 12 10:40:49 2020
read: IOPS=2535k, BW=9903MiB/s (10.4GB/s)(48.4GiB/5001msec)
clat (nsec): min=38, max=10680, avg=40.94, stdev= 4.20
lat (nsec): min=107, max=10751, avg=110.78, stdev= 6.13
...
```
Notice that the last ETA update line indicates that there are still 5s
of runtime left even though the job has finished. This occurs because
the while loop in helper_thread_main() finishes …
> helper_thread: better handle select() return value

- engines/rados.c
This change protects against problems when closing connection to ceph,
while some aio are in flight.
> engines/rados: Added waiting for completion on cleanup.

- engines/rados.c
The Travis-CI Ubuntu 18.04 build fails because the type for `completed_more_io`
was changed from `pthread_cond_t` to `thread_cond_t`:
https://travis-ci.org/github/axboe/fio/jobs/687073515
Change it back to `pthread_cond_t`.
The original code actually builds without error in my local Ubuntu 18.04 build environment but it fails in Travis-CI's Ubuntu 18.04 build environment.
Fixes: 1e30d8d005a568169c0749f5fc6fb2d5f09dcc97 ("engines/rados: Added
waiting for completion on cleanup.")
Signed-off-by: Vincent Fu <vincent.fu@wdc.com>
> engines/rados: fix build issue with thread_cond_t vs pthread_cond_t

- backend.c
- options.c
In many high-performance systems today it is possible to exceed 4GiB/s
throughput. Therefore convert the rate and rate_min options from
FIO_OPTS_INT to FIO_OPTS_ULL.
Fixes #716.
Signed-off-by: Stephen Bates <sbates@raithlin.com>
> rate: Convert the rate and rate_min options to FIO_OPTS_ULL

- fio.h
- init.c
- lib/rand.c
- lib/rand.h
- After 140a6888 ("rate: Convert the rate and rate_min options to
FIO_OPTS_ULL") landed 32-bit/LLP64 platforms need additional changes
to cope with 64 bit I/O rate values
- The seed is 64 bit but was being being truncated to 32 bits in
td_fill_rand_seeds_internal() on bit/LLP64 platforms
Prior to this commit when running an fio compiled with
CC=clang-9 ./configure \
--extra-cflags="-fsanitize=undefined,implicit-integer-truncation "
"-fno-builtin"
using this job
./fio --ioengine=null --bs=1M --rate=6G --rate_min=5G --name=test --size=100G
warnings like the following were produced
init.c:996:27: runtime error: implicit conversion from type 'uint64_t' (aka 'unsigned long long') of value 5942511153023025289 (64-bit, unsigned) to type 'unsigned int' changed the value to 2914779273 (32-bit, …
> Fix 32-bit/LLP64 platform truncation issues

- HOWTO
- fio.1
- t/jsonplus2csv_test.py
- t/latency_percentiles.py
- t/readonly.py
- t/run-fio-tests.py
- t/steadystate_tests.py
- t/strided.py
- t/zbd/run-tests-against-regular-nullb
- t/zbd/run-tests-against-zoned-nullb
Jens, please consider this series of patches that mainly focus on improving the test scripts.
They do the following:
- reduce test file size for jsonplus2csv_test to better accommodate low resource platforms
- improve error handling in run-fio-tests.py
- only run cmdprio_percentage latency tests if root
- document that root is required for cmdprio_percentage option
- speed up testing with max-jobs
- improve zbd test script error handling
> Testing improvements

- HOWTO
- cconv.c
- fio.1
- fio.h
- io_u.c
- options.c
- server.h
- thread_options.h
Currently, latency_target run will exist once fio find the highest queue
depth that meets latency_target. Add option latency_run. If set, fio will
continue running and try to meet latency_target by adusting queue depth.
Signed-off-by: Song Liu <songliubraving@fb.com>
> Add option latency_run to continue enable latency_target

- Makefile
SuperH compile currently fails with:
```
/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sh4-buildroot-linux-uclibc/8.3.0/../../../../sh4-buildroot-linux-uclibc/bin/ld: t/io_uring.o: in function `submitter_fn':
/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output-1/build/fio-3.19/t/io_uring.c:131: undefined reference to `arch_flags'
/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sh4-buildroot-linux-uclibc/8.3.0/../../../../sh4-buildroot-linux-uclibc/bin/ld: /usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-0/output-1/build/fio-3.19/t/io_uring.c:367: undefined reference to `arch_flags'
collect2: error: ld returned 1 exit status
```
Fix that by ensuring we have a stub arch.o with …
> Makefile: fix build of io_uring on sh4

- lib/pattern.c
- lib/pattern.h
- options.c
This series of three patches is the result of the analysis of a Coverity complaint about the parse_format() function.
> Fix parse_format()

- .travis.yml
- t/steadystate_tests.py
- t/strided.py
Jens, please consider this pull request. It changes two test scripts to refer to python3 and updates the travis-ci settings accordingly.
I no longer have SAS SSDs available to test t/sgunmap-perf.py and t/sgunmap-test.py. So those remain unchanged.
Apart from the two sgunmap-*.py scripts, all of the other python test scripts now use the python3 interpreter.
> Transition active test scripts to python3

- pshared.c
FreeBSD supports it, but NetBSD/OpenBSD don't.
```
FreeBSD
POSIX pshared support         yes
```
```
NetBSD
POSIX pshared support         no
```
> pshared: fix comment on supported platforms

- init.c
latency_window has unit of microseconds, and is compared against
usec_window. Therefore, there is no need to fix it up to nanoseconds.
Signed-off-by: Song Liu <songliubraving@fb.com>
> fix unit of latency_window

- engines/libiscsi.c
On authentication failure when connecting to an iscsi server, fio will
print "sicsi: failed to connect to LUN : Failed to log in to target.".
This change fixes a typo, changing sicsi to iscsi.
Signed-off-by: Raphael Norwitz <raphael.norwitz@nutanix.com>
> Fix typo in libiscsi error message

- pshared.c
- zbd.c
- zbd.h
This is what I came up with while reviewing recent patches for the zoned block device code (zbd.[ch]).
> A few small fixes for the zbd code

- lib/seqlock.h
I might be off here, but it seems like ``seqlock.sequence`` should be ``unsigned`` to avoid comparing signed with unsigned in the function ``read_seqlock_retry()``.
> Changed signedness of seqlock.sequence fixing comparison-warning

- engines/pmemblk.c
Reported-by: Yi Zhang <yi.zhang@redhat.com>
Tested-by: Yi Zhang <yi.zhang@redhat.com>
Fixes: e9c7be0e32e6 ("pmemblk: Fix a memory leak")
> Unbreak the pmemblk engine

- engines/io_uring.c
I'm seeing a slowdown in io_uring performance on a POWER9 box when
the userspace and kernel polling threads are on two cores that
share an L2 cache.
fio_ioring_cqring_reap() always stores to the completion queue head
pointer, even if nothing was reaped and the value hasn't changed.
Changing this to only update the head pointer when it changes results
in a 95% improvement in performance on this particular test.
Signed-off-by: Anton Blanchard <anton@ozlabs.org>
> io_uring: Avoid needless update of completion queue head pointer

- Makefile
With recent changes to Makefile dev-dax skips building. This patch fixes that.
Signed-off-by: Harish <harish@linux.ibm.com>
> Fix: dev-dax engine building with make

- tools/fio_generate_plots
Since log files for latencies have values in nanoseconds in order to get microseconds we divide by 1000
and for milliseconds by 1000000
> fio_generate_plots: fix scale on gnuplot graphs

- configure
- Bail out if the probe fails when the user is explicitly enabling the
cuda, libiscsi or libnbd ioengines or the libaio io_uring option
- Normalize some of the code that deals with enabling/disabling the
above options
Fixes: https://github.com/axboe/fio/issues/1052
> configure: fail when explicit enabling doesn't succeed

- ci/travis-install.sh
cf6d8924684125b927e55471e58bad5a246e859d ("travis: enable libiscsi and cuda ioengines") made the travis x86 cross compile builds fail because pkg-config was still looking for 64 bit libraries. This patchset brute forces it way around the problem by making travis install a 32 bit pkg-config for that build.
> Fix travis libiscsi

- rate-submit.c
This patch has been tested by running the following shell command:
for ((i=0;i<1000;i++)); do echo $i; python3 t/run-fio-tests.py -o 10; done
Fixes: d28174f0189c ("workqueue: ensure we see deferred error for IOs")
> Prevent that fio hangs when using io_submit_mode=offload

- cconv.c
- examples/exitwhat.fio
- fio.1
- server.h
- thread_options.h
Fixes: 64402a8 ("Expand choices for exitall")
Fixes: https://github.com/axboe/fio/issues/1065
Signed-off-by: André Wild <wild.andre.ae@gmail.com>
> Use unsigned short type for exit_what and stonewall

- oslib/asprintf.c
- oslib/asprintf.h
```oslib/asprintf.h``` needs to include ```<stdarg.h>``` for ```va_list```.
This started to appear on NetBSD since
38b00241e3("num2str(): Use asprintf() instead of malloc()").
```
In file included from lib/num2str.c:7:0:
lib/../oslib/asprintf.h:5:45: error: unknown type name 'va_list'; did you mean '__va_list'?
int vasprintf(char **strp, const char *fmt, va_list ap);
^~~~~~~
__va_list
CC lib/pattern.o
gmake: *** [Makefile:447: lib/num2str.o] Error 1
```
> oslib: fix asprintf build failure

- filelock.c
Earlier solution to increase MAX_FILELOCKS for high parallelism might not be necessary given the wrong assertion
`> fio: filelock.c:182: __fio_lock_file: Assertion !trylock' failed. `
https://github.com/axboe/fio/commit/43661a66a8c3b9fb5ff28b463c9ab0aac91a0355
> filelock: fix wrong file trylock assertion.

- .appveyor.yml
When the test_script stage fails the artifacts stage isn't run. This is
problematic because the long running tests (on all platforms) can be
flaky and Windows folk are accustomed to not having to do builds
themselves when testing the tip of a project. This could lead to a
situation where no there's no pre-built Windows binaries due to a
spurious failures...
Solve the above by moving the smoke test and artifact upload to be
earlier, remove a useless use of bash during smoke Appveyor smoke
testing and change the "Deployment name" from msi to fio.msi.
> ci: always upload Windows MSI if smoke test passes

- zbd.c
This patch fixes the following Coverity complaint:
CID 292491 (#1 of 1): Missing unlock (LOCK)
missing_unlock: Returning without unlocking zb->mutex.
Fixes: bfbdd35b3e8f ("Add support for zoned block devices")
> zbd: Add a missing pthread_mutex_unlock() call

- init.c
In the current code, calling --enghelp=<engine> always return 0.
But fio_show_ioengine_help() implemented a return code to inform when an engine is present or not.
This commit makes fio returning fio_show_ioengine_help() value when calling --enghelp=<engine>
A typical use case is detecting which engine is available on a given fio build.
It is possible to use the return code to determine if a given engine is available or not :
[user@host]# fio --enghelp=libaio
userspace_reap          : Use alternative user-space reap implementation
[user@host]# echo $?
0
[user@host]#fio --enghelp=io_uring
fio: engine io_uring not loadable
IO engine io_uring not found
[user@host]# echo $?
1
Signed-off-by: Erwan Velu <e.velu@criteo.com>
> init: exiting with fio_show_ioengine_help return code

- parse.h
axboe#1096 shows that a compiler complains an arithmetic on a pointer to void error when -Wpointer-arith is turned on in Makefile. Although there are many violating instances, we only fix the one in parse.h because it is shared across many core source code files. This patch fixes the arithmetic on a pointer to void issue by casting it to a uintptr_t type first and perform manipulation, and then cast it back to void* type.
> Update parse.h to avoid arithmetic on a pointer to void cast (#1096)

- oslib/getopt_long.c
Issue #1100 shows that an address sanitizer(ASAN) complains about a few
global variables that are initialized globally in the getopt_long.c file.
We look into these variables and found they do not need to be initialized
globally. This patch fixes the issue by cleaning up the global
initialization for these variables.
Signed-off-by: Cheng Li <chenglii@cs.rutgers.edu>
> getopt_long: avoid variable global initialization

- HOWTO
- engines/glusterfs.c
- engines/ime.c
- engines/libpmem.c
- filesetup.c
- fio.1
- options.c
This is my first stab at this, there might be more places that need to be touched.
What do you think about my approach of extending --sync rather than adding a --dsync? And about just storing the flag bits in `td->o.sync_io`?
See  #1033
> Add O_DSYNC support

- Makefile
- engines/libhdfs.c
Commit 08dc3bd50 initialized the io engine before the io_u buffers. The
unintended consequence for the libhdfs io engine was that the HDFS
connection was not established before attempting to open HDFS file
handles. This caused a NPE in the java layer on start-up preventing the
libhdfs io engine from being able to be used.
Also fix usage of JAVA_HOME environmental variable.
> Swap fio_hdfsio_init and fio_hdfsio_io_u_init

- ioengines.h
increment FIO_IOOPS_VERSION to reflect changes made to struct io_u in versions 3.22+
> ioengines: increment FIO_IOOPS_VERSION

- eta.c
- iolog.h
- stat.c
This commit enables agg logs to grow to MAX_LOG_ENTRIES, like any thread logs.
Fixes: https://github.com/axboe/fio/issues/1113
Co-authored-by: Sitsofe Wheeler <sitsofe@yahoo.com>
Tested-by: Panagiotis Moustafellos <pmoust@elastic.co>
Signed-off-by: Panagiotis Moustafellos <pmoust@elastic.co>
> Grow bandwidth log stats to MAX_LOG_ENTRIES

- stat.c
With the current FIO version, we're seeing the interval for writing 
the BW and IOPS logs increase by 1 msec over time.  The --log_avg_msec
option is used to set the time interval for logging BW and IOPs.  See
the following file for an example:
[int-creep-example.txt](https://github.com/axboe/fio/files/5503565/int-creep-example.txt)
This issue will cause dip ( low ) in IOPS and BW plot vs time because 
parsing/plot tool can't get correct sum total IOPS and BW from 
multiple jobs when there is 1-2us increment in timestamp.
The issue was introduced in version 3.18 with the following 
commit - 31eca64.  And these changes made it slightly better: 0f77d30,
and PR #973 (0e59dd6), but the problem still exists.
This commit also contains the change from PR #982.  I believe we need
both changes to …
> stat: Prevent the BW and IOPs logging interval from creeping up

- HOWTO
- Makefile
- configure
- engines/libcufile.c
- examples/libcufile-cufile.fio
- examples/libcufile-posix.fio
- fio.1
- optgroup.c
- optgroup.h
Please review. I hope that the code adheres to the patterns I observed in the other I/O engines, and am sure there are things that need to be corrected.
All feedback is welcome.
As of GPUDirect Storage 0.9.0, the configure invocation is:
```
$ CFLAGS="-I/usr/local/cuda/include -I/usr/local/cuda/lib64" LDFLAGS="-L/usr/local/cuda/lib64" ./configure --enable-cufile
```
GPUDirect Storage (GDS) is obtained from here: https://developer.nvidia.com/gpudirect-storage
GDS requires a Tesla or better GPU, x86_64 CPU, Ubuntu OS 18 or 20, MOFED 5.1 and Mellanox HCA >= ConnectX-5.
----
The cufile I/O engine uses NVIDIA GPUDirect Storage (GDS) cuFile API to perform
I/O directly against GPU buffers via nvidia-fs and a GDS-supported filesystem.
'configure --enable-cufile' enables the cufile engine.
CFLAGS …
> Add cufile I/O engine

- examples/cpp_null.fio
- examples/cross-stripe-verify.fio
- examples/dev-dax.fio
- examples/e4defrag.fio
- examples/e4defrag2.fio
- examples/exitwhat.fio
- examples/falloc.fio
- examples/fio-rand-RW.fio
- examples/fio-rand-read.fio
- examples/fio-rand-write.fio
- examples/fio-seq-RW.fio
- examples/fio-seq-read.fio
- examples/fio-seq-write.fio
- examples/fsx.fio
- examples/jesd219.fio
- examples/libpmem.fio
- examples/libzbc-rand-write.fio
- examples/null.fio
- examples/pmemblk.fio
- examples/steadystate.fio
- examples/surface-scan.fio
- examples/waitfor.fio
- examples/zbd-rand-write.fio
The examples/ directory is often used as a starting point for new jobs or tests but many has incorrect/useless syntax which could confuse users.
Let's get all examples using the same syntax.
> Uniform examples usage

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/SUPPORT.md
- REPORTING-BUGS
Add a load of templates and documentation to help guide GitHub users who file reports. This likely needs some improvement/consolidation but you can get a preview via https://github.com/sitsofe/fio/issues/new/choose .
> Create documentation/templates to help GitHub users

- io_u.c
Problem happens when --openfiles is set and file_service_type != FIO_FSERVICE_SEQ.
In function `__get_next_file`, we decrement file_service_left and if 0, we select
next file to operate on.
However, `get_next_file_rand` can return -EBUSY if too many files are already opened,
and `__get_next_file` exits with error.
In next invocation of `__get_next_file`, we decrement file_service_left again (from 0),
wrapping around to 2^32-1, effectively locking `__get_next_file` to always select the same.
> io_u: Fix bad interaction with --openfiles and non-sequential file selection policy

- HOWTO
- engines/cpu.c
- examples/cpuio.fio
- fio.1
This commit adds cpumode option into the cpuio engine.
By default, cpumode=noop to keep the current behavior.
If cpumode is set to qsort, fio will use a qsort algorithm
instead of the noop instructions to load the processor.
This mode will consume more cpu power and will be useful to
increase the pressure on the thermal and electrical components.
The expected cpu load is selected as per noop via the cpuload option.
qsort() consumes a lot of energy so the duration
of every loop will vary over time as the power management & cpu clock
changes. To ensure a proper calibration, the thinktime is adjusted after every
qsort() computation to be as precise as possible.
To give an order of magnitude, on an AMD 7502P (TDP=180W) :
cpuload=30, numjobs=64: packagewatt = 134W
cpuload=50, numjobs=64: …
> engines/cpu: Adding qsort capabilities

- engines/cpu.c
Make sure that the third td_vmsg() argument is a fully expanded string and
also that the fourth argument is a string argument. This was detected by
Coverity.
Fixes: b213922390fe ("engines/cpu: style cleanups")
> engines/cpu: Fix td_vmsg() call

- lib/num2str.c
Fix #1117
example:
The result of num2str(11999999999999, 4, 1, 0, N2S_NONE) should be "12.0G", but current result is "11.0G". 
Signed-off-by: Jiahao Li <gloit042@gmail.com>
> num2str: fix precision loss bug when the fractional part is close to 1

- configure
- Use a different method to avoid weak linking
- Fix the inability to compile on old OSX 10.11 by adding a shim for clock_gettime().
It's a bit hacky to shim clock_gettime() but it looks like fio has grown a dependence on it being available (all the CI platforms fio builds for have it so it's understandable).
@axboe, @bvanassche any thoughts?
> Fix compilation on macOS

- HOWTO
- cconv.c
- filesetup.c
- fio.1
- fio.h
- init.c
- lib/gauss.c
- lib/gauss.h
- lib/zipf.c
- lib/zipf.h
- options.c
- server.h
- t/genzipf.c
- thread_options.h
This change affects options random_distribution and file_service_type.
For pareto, zipf and gauss distribution a contept of `center` is implemented.
It allows to fix in place a value that is most probable to access.
Example:
fio --randseed=1 --ioengine=libaio --rw=randwrite --nrfiles=16 --bs=4k \
--size=256m --allow_file_create=1 --write_iolog=log.txt \
--file_service_type=gauss:10:0.1 --filename_format=object.\$filenum --name=x
cat log.txt |grep write |cut -f 1 -d " " |sort |uniq -c | sort -n | \
sed "s/[.]/ /" | while read a b c; do echo $c $b $a; done |sort -n
0 object 13429
1 object 17928
2 object 14724
3 object 7845
4 object 2476
5 object 468
6 object 44
7 object 3
12 object 24
13 object 318
14 object 1795
15 object 6482
> Extend flexibility of non-uniform random distributions

- options.c
Google's OSS-fuzz turned up a heap overrun when substituting keywords in
job files. To reproduce compile fio with address sanitizer options like
the following
```
LDFLAGS="-fsanitize=address" ./configure --disable-optimizations \
--extra-cflags="-fsanitize=address"
```
The issue is demonstrated by the following job:
```
% printf '[t]\ndescription=$ncpus_' | fio --parse-only -
opt = 'description=$ncpus'
=================================================================
==22547==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603000001863 at pc 0x000107a833c9 bp 0x7ffee82ac260 sp 0x7ffee82ac258
READ of size 1 at 0x603000001863 thread T0
#0 0x107a833c8 in fio_keyword_replace options.c:5124
#1 0x107a7c6ab in dup_and_sub_options options.c:5158
#2 0x107a7bb4f in fio_options_parse …
```
> options: fix keyword substitution heap overrun

- options.c
- parse.c
Google's OSS-fuzz turned up a buffer overrun with value of the filename
option due to an overrun in a MAX_PATH sized buffer. To reproduce
compile fio with address sanitizer options like the following
```
LDFLAGS="-fsanitize=address" ./configure --disable-optimizations \
--extra-cflags="-fsanitize=address"
```
The issue is demonstrated by the following job:
```
% COUNT=$(getconf PATH_MAX /); printf "[t]\nfilename=%${COUNT}s" \
| sed 's/ /@/g' | fio --parse-only -
=================================================================
==45748==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee8e35780 at pc 0x00010735a343 bp 0x7ffee8e35270 sp 0x7ffee8e34a08
WRITE of size 1025 at 0x7ffee8e35780 thread T0
#0 0x10735a342 in wrap_vsprintf …
```
> options: fix buffer overrun

- configure
Running fio on an ESX host fails due to the lack of support for file
descriptor based notifications of timer expiration.  This change
bypasses patch 696378af added to increase timer accuracy.
Signed-off-by: Brian 'Redbeard' Harrington <redbeard@redhat.com>
> bug: ESX does not have timerfd support

- configure
The current test for libpmem in 'configure' fails
in the following way:
```
$ gcc test.c -lpmem
test.c: In function ‘main’:
test.c:6:27: warning: passing argument 2 of ‘pmem_is_pmem’ \
makes integer from pointer \
without a cast [-Wint-conversion]
6 |   rc = pmem_is_pmem(NULL, NULL);
|                           ^~~~
|                           |
|                           void *
In file included from test.c:1:
/usr/include/libpmem.h:92:43: note: expected ‘size_t’ \
{aka ‘long unsigned int’} but argument \
is of type ‘void *’
92 | int pmem_is_pmem(const void *addr, size_t len);
|                                    ~~~~~~~^~~
```
Fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fio: fix detecting libpmem

- HOWTO
- fio.1
- init.c
We been using fio heavily, but getting it to put an IP into filename was a struggle.
Previously we had to specify `directory=/` in config, which would prepend /<ip> to any filenames. Having explicit format string for this seems better :)
> $clientuid keyword to differentiate clients in client/server mode

- engines/libpmem.c
- file.h
- filesetup.c
- ioengines.h
In some cases (e.g. engine marked as diskless) files are not laid out.
If the first job is a read job, results are higher than expected
(because reading zero page). Each engine should deliver func to
prepopulate file with data to avoid this situation.
Signed-off-by: Łukasz Stolarczuk <lukasz.stolarczuk@intel.com>
> filesetup: add engine's io_ops to prepopulate file with data

- configure
This removes the symbol definitions for CLOCK_MONOTONIC_PRECISE and CLOCK_MONOTONIC_RAW.
Those are no longer used in the code and the respective probes were removed in commits 187f39063e1b0a7baeda20a9f4f2406327ec0d41 and 69212fc41c0420f8caf272a0cc270194edbddfe7.
I just stumbled upon this. In case these definitions are there for a reason, please feel free to close this PR.
> configure: remove unused CLOCK_MONOTONIC_* symbols

- engines/io_uring.c
This rename variable __errno to init_err, because Android NDK already uses __errno in errno.h, then it will throw a compilation error `called object type 'int' is not a function or function pointer` if we declare a variable as same name.
> engines/io_uring: fix compilation conflict with Android NDK

- engines/falloc.c
fallocate supoport for blockdevices was added five years ago.
It is time to stress-test it via fio.
> engines/falloc: add blockdevice as a target

- iolog.c
During fio replay, the input file would be checked first by is_blktrace()
if it is a blktrace output file. If so, however, this would treat the
read_iolog option as one single file and ignore multiple files seperated by ":"
This commit contains the fixation that read input file name by index
before doing the check
Signed-off-by: luye <luye.yelu@bytedance.com>
> Fix reading multiple blktrace replay files

- backend.c
- init.c
- options.c
- options.h
Fix the following LeakSanitizer warnings:
Indirect leak of 224 byte(s) in 7 object(s) allocated from:
#0 0x7f7377b21bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
#1 0x563951e5e09d in add_to_dump_list /home/nks/src/fio/parse.c:1135
#2 0x563951e5e09d in add_to_dump_list /home/nks/src/fio/parse.c:1127
#3 0x563951e5e09d in parse_cmd_option /home/nks/src/fio/parse.c:1162
Indirect leak of 43 byte(s) in 7 object(s) allocated from:
#0 0x7f7377aaa3dd in strdup (/lib/x86_64-linux-gnu/libasan.so.5+0x963dd)
#1 0x563951e5e0a8 in add_to_dump_list /home/nks/src/fio/parse.c:1136
#2 0x563951e5e0a8 in add_to_dump_list /home/nks/src/fio/parse.c:1127
#3 0x563951e5e0a8 in parse_cmd_option /home/nks/src/fio/parse.c:1162
Indirect leak of 36 byte(s) in 7 object(s) allocated from:
#0 0x7f7377aaa3dd …
> options: free dump options list on exit

- HOWTO
- engines/rados.c
- fio.1
Changed connection procedure so it no longer attempts to create objects.
This change will affect tests that read objects without creating them first.
> engine/rados: Remove mandatory creation

- parse.h
When compiling an out of tree ioengine, such as the SPDK fio plugin,
which has -Wextra in CFLAGS, the compiler gives the following warning:
parse.h: In function ‘parse_is_percent’:
parse.h:134:13: warning: comparison of integer expressions of different signedness: ‘long long unsigned int’ and ‘int’ [-Wsign-compare]
Since this warning was introduced recently by fio
commit b75c0fae6612 ("parse: simplify parse_is_percent()"),
and since this is the only warning seen when compiling the SPDK fio
plugin, readd the ULL prefix to parse_is_percent().
Fixes: b75c0fae6612 ("parse: simplify parse_is_percent()")
Signed-off-by: Niklas Cassel <niklas.cassel@wdc.com>
> parse: fix parse_is_percent() warning

- init.c
zbd_init_zone_info() has a comment that it only works correctly if it
called before the first fio fork() call.
However, right now, there is nothing that ensures this.
If the user specifies --create_serialize=0 and --numjobs=2, each thread
will get their own version of zbd_info.
zbd_info contains one mutex per zone, so if the threads get different
zbd_info, two threads can manage to lock the same zone at the same time,
which will lead to I/O errors.
Explicitly disallow --zonemode=zbd together with --create_serialize=0,
so that we know that all threads will use the same zbd_info, instead of
silently misbehaving.
Analysis:
setup_files() calls zbd_init_files() which calls zbd_init_zone_info().
zbd_init_zone_info() does a for_each_td(), where it checks if zbd_info
(for the same filename) has …
> init: zonemode=zbd does not work with create_serialize=0

- HOWTO
- engines/librpma_fio.c
- engines/librpma_fio.h
- engines/librpma_gpspm.c
- examples/librpma_gpspm-server.fio
- fio.1
The performance of the librpma_gpspm engine depends heavily
on how much CPU power it can use to its work.
One can want either to take all available CPU power
and see what the maximum possible performance is
or configure it less aggressively and collect the results
when the CPU is not solely dedicated to doing this one task.
The librpma_gpspm engine allows toggling between one and another
by either waiting for incoming requests in the kernel
using rpma_conn_completion_wait() (busy_wait_polling=0)
or trying to collect the completion as soon as it appears
by polling all the time using rpma_conn_completion_get()
(busy_wait_polling=1).
Signed-off-by: Oksana Salyk <oksana.salyk@intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> rpma: gpspm: introduce the busy_wait_polling toggle

- gettime.c
- os/os-aix.h
- os/os-android.h
- os/os-dragonfly.h
- os/os-freebsd.h
- os/os-hpux.h
- os/os-linux.h
- os/os-mac.h
- os/os-netbsd.h
- os/os-openbsd.h
- os/os-solaris.h
874d55e50c("os/os-linux: add pthread CPU affinity helper") and a few
commits after that broke compilation on non-Linux platforms which support
`pthread_getaffinity_np()`.
If the C code is to test `CONFIG_PTHREAD_GETAFFINITY`, it should just
directly use `pthread_getaffinity_np()` instead of definining a wrapper
that is not specific to pthread.
> gettime: Fix compilation on non-Linux with pthread_getaffinity_np()

- stat.c
Assuming that "int" is 32-bit, for high bandwidth values (> 21.5 GB/s)
the expression "mean * 100" will cause an integer overflow before the
conversion to "double" happens.
Tested on the latest commit on `master`: 30bec59eab3908b681cbc2866179f7166a849c83
I was using a config with 8 jobs reading sequentially from a RAID 0 of multiple NVMe SSDs, reaching an aggregate bandwidth of 40+ GB/s (the config has `group_reporting=1`). Using a JSON output, I saw the following:
```
"bw_agg" : -2.289580,
```
And after investigating I saw this was caused by the integer overflow mentioned above.
> stat: fix integer overflow in convert_agg_kbytes_percent

- engines/libpmem.c
- examples/libpmem.fio
- set file open/create mode always to RW,
- do not call drain on close, it's redundant,
- code and example cleanup.
> engines/libpmem: minor fixes and code cleanup

- Makefile
- ci/appveyor-install.sh
Signed-off-by: Erwan Velu <e.velu@criteo.com>
> Avoid stpcpy issue when building with clang 12

- tools/plot/fio2gnuplot
The logging format updates documented in 1a953d97 were never
propagated to fio2gnuplot, which since then has been failing with a
ValueError exception.
This commit explicits limits fio2gnuplot to only reading the first
4 columns in the log file.
> fix fio2gnuplot to work with new logging format

- configure
Do what check_min_lib_version() does to not print the error message
when pkg-config doesn't exist.
```
DAOS File System (dfs) Engine no
./configure: pkg-config: not found
NFS engine                    no
```
> configure: silence "pkg-config: not found"

- fio.h
- io_u.c
from testing we can see that on small file sizes with high dedup percentage requested the actual dedup percentage resulted is much lower than expected.
for example:
`./fio --name=bar -rw=randwrite --bs=4096 --size=1mb --dedupe_percentage=99 --direct=1`
when checking the actual percentage received -  we got 34% instead of 99%:
`./t/fio-dedupe -o 1 bar.0.0 `
```
Will check <bar.0.0>, size <1048576>, using 15 threads
Threads(15): 256 items processed
Extents=256, Unique extents=169
De-dupe ratio: 1:0.51
Fio setting: dedupe_percentage=34
```
the reason to that is since in high dedup percentage the buf_state_prev would likely be chosen:
```
static struct frand_state *get_buf_state(struct thread_data *td)
{
...
if (v <= td->o.dedupe_percentage)
return &td->buf_state_prev;
...
}
```
however, …
> dedupe: fixing bug with subsequent dedupe buffer generation

- server.c
Reported-by: Manuel Gotin <manuel.gotin@ibm.com>
Signed-off-by: Tuan Hoang <tmhoang@linux.ibm.com>
> server: fix missing le32_to_cpu conversion when opcode is FIO_NET_CMD_TEXT

- verify.c
Fix an error triggered by double releasing the lock. 
Fixes: https://github.com/axboe/fio/issues/1254.
Signed-off-by: Anson Lo ycaibb@gmail.com
> Fix an error triggered by double releasing the lock

- HOWTO
- engines/dfs.c
- fio.1
A few changes were done to the pool connect and container open API
in DAOS 1.3+. UUID string or label are now passed via the API
instead of uuid_t structures. Change the dfs engine accordingly.
Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>
> engines/dfs: add support for 1.3 DAOS API

- t/one-core-peak.sh
Associated to fio, the t/io_uring test is used to compute the max IOPS a
single core can get.
Jens published several times the procedure he uses, but trying to
reproduce this setup is error-prone. It's easy to miss a configuration
and get a different result.
This script is about setting up a common setup to reproduce these runs.
From the fio directory, execute like the folliowing :
[user@fio] t/one-core.sh /dev/nvme0n1 [other drives]
system: Checking configuration
Warning: For better performance, you should enable nvme poll queues by setting nvme.poll_queues=32 on the kernel commande line
nvme0n1: set none as io scheduler
nvme0n1: iostats set to 1. Disabling.
nvme0n1: nomerge set to 0. Disabling.
system: End of system checks
io_uring: Running taskset -c 0,12 t/io_uring -b512 -d128 -c32 …
> t/one-core.sh: Adding script to run the one-core io benchmark

- t/io_uring.c
Without these \n, the new options were baddly printed
Signed-off-by: Erwan Velu <e.velu@criteo.com>
> t/io_uring.c: Adding \n on help

- server.c
- t/io_uring.c
Handle Windows-specific signal SIGBREAK the same as SIGINT (Ctrl+c) in the few places that don't already behave that way.
Signed-off-by: Brandon Paupore <brandon.paupore@wdc.com>
> add signal handlers for Windows SIGBREAK

- backend.c
This fixes an issue where IOPS targets were not met
when the `bs` parameter was not given explicitly, such
as when using `bssplit`.
Fixes #1290
> Use min_bs in rate_process=poisson

- README
Typo fix in README.
Signed-off-by: Jean-Francois Panisset <panisset@gmail.com>
> Small typo fix

- parse.c
Option parser does not properly handle 'sync_file_range' option with
multiple flags.  It was due to opt_len() only use ':' as delimiter, so
only last flag in comma-separated list have effect.
This patch adds ',' as a delimiter.  All flags are correctly ORed now.
Fixes: https://github.com/axboe/fio/issues/1234
Signed-off-by: Oleg Latin <oleglatin@yandex-team.ru>
> parse: handle comma-separated options

- os/os-linux.h
Issue #1239 shows a crash on a FUJITSU/A64FX ARM platform at the
following line:
crc/crc32c-arm64.c:
64                 t1 = (uint64_t)vmull_p64(crc1, k2);
On armv8 PMULL crypto instructions like vmull_p64 are defined as
optional (see
https://github.com/google/crc32c/pull/6#issuecomment-328713398 and
https://github.com/dotnet/runtime/issues/35143#issuecomment-617263508 ).
Avoid the crash by gating use of the hardware accelerated ARM crc32c
path behind runtime detection of PMULL.
Fixes: https://github.com/axboe/fio/issues/1239
Tested-by: Yi Zhang <yi.zhang@redhat.com>
> os: detect PMULL support before enabling accelerated crc32c on ARM

- .github/workflows/ci.yml
- ci/actions-install.sh
- t/io_uring.c
Jens, please consider these patches.
They fix the 32-bit GitHub Actions build problem and re-enable testing for the 32-build. (Latency measurement for t/io_uring is broken on 32-bit platforms, though).
Also, I fixed a couple t/io_uring issues found while I was investigating the build problem.
> GitHub actions i686, small t/io_uring fixes

- configure
- engines/librpma_fio.c
- engines/librpma_fio.h
Add support for File System DAX. File System DAX is handled in a different way than Device DAX:
1) In case of File System DAX, each thread uses a separate file
from this file system and no offset is needed. In case of Device DAX,
each thread uses a separate offset within the same Device DAX.
2) File System DAX requires `rpma_mr_advise(3)`(`ibv_advise_mr(3)`)
to be called for the registered memory to avoid page faults
and degraded performance.
The librpma engine requires librpma>=v0.10.0 with `rpma_mr_advise(3)`.
Ref: #1238
Signed-off-by: Lukasz Dorau <lukasz.dorau at intel.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axboe/fio/1329)
> rpma: add support for File System DAX

- HOWTO
- fio.1
Setting `size` does not actually limit the total size of files created.
Fixes: axboe#1218
> Fix `filesize` description

- HOWTO
- fio.1
FreeBSD 11 (2016, EOL'd) added fdatasync(2).
(FWIW DragonFlyBSD added it recently in master branch, not yet in a release.  For Windows, it might be interesting to look into NtFlushFileBuffersEx() with FLUSH_FLAGS_FILE_DATA_SYNC_ONLY.)
> Update comments about availability of fdatasync().

- .github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which fio already runs.
> ci/Github actions: add CIFuzz integration

- backend.c
Using rate_min/rate_iops_min when io_submit_mode=offload option is set
leads to intermittent asserts and doesn't work. The variable comp_time
is never set in do_io in backend.c in the offload case, and comp_time is
then used in the calls to check_min_rate. The time computations in
check_min_rate either assert and terminate fio, or return meaningless
values, so any rate checking is not correct.
This first issue is fixed by adding a call to fio_gettime in the
offloading case. Once that is done though, there is still another
problem remaining. When the min rate is not achieved (with the
offloading option), fio detects it and tries to exit but fails. It ends
up in a state where ctrl-C will not cause an exit either. This happens
because cleanup_pending_aio(td) in the error case hangs in its …
> Fix issues (assert or uninit var, hang) with check_min_rate/offloading

- eta.c
The base passed to num2str in the ETA display code passed the wrong
base (0 instead of 1). Additionally, je->sig_figs was never set and
defaulted to 0. Both of these caused the desired range in the ETA code
to always display 0-0 when rate or rate_min was specified.
Signed-off-by: Nick Neumann nick@pcpartpicker.com
> Fix ETA display when rate and/or rate_min are specified

- init.c
When using the :<nr> suffix with random reads or writes, the initial
offset would be set to 0 for the first nr-1 operations. This happened
because td->ddir_seq_nr was initialized to the specified option value,
when it needs to always be initialized to 1, so that the first call to
get_next_offset leads to choosing a new random offset for the first nr
operations.
Signed-off-by: Nick Neumann nick@pcpartpicker.com
> Fix :<nr> suffix with random read/write causing 0 initial offset

- backend.c
- fio.h
- libfio.c
This is a cleanup of __check_min_rate. In looking at stuff for previous fixes,
it seems like there are a lot of boolean checks of things that are always true
or always false. I'll explain my reasoning for each change; it is possible I'm
missing something somehow but I've run through it a few times.
Here's my logic:
1) td->rate_bytes and td->rate_blocks are 0 on first call to __check_min_rate,
and then are the previous iteration's value of td->this_io_bytes and
td->this_io_blocks on subsequent calls
2) bytes and iops are the current iteration's values of td->this_io_bytes and
td->this_io_blocks
3) The values of td->this_io_bytes and td->this_io_blocks are monotonic with
respect to each call of __check_min_rate
Therefore, bytes and iops are always greater than or equal to td->rate_bytes
and …
> Cleanup __check_min_rate

- ci/travis-install-pmdk.sh
- t/one-core-peak.sh
- tools/fio_generate_plots
Originally submitted as https://www.spinics.net/lists/fio/msg09882.html. The debianutils deprecation mentioned in the original has been since reverted, but I think these changes would be good ones nevertheless.
> ci, t, tools: use `command` and `type` instead of `which`

- engines/cmdprio.c
Fix three occurrences of the following clang compiler warning:
warning: suggest braces around initialization of subobject [-Wmissing-braces]
> Fix three compiler warnings

- parse.c
- fixed memory leak, which is happening when parsing options, claimed by ASAN
> fixed memory leak detected by ASAN in parse.c

- backend.c
- fixed memory leak in parent process detected by ASAN when forking and not freeing memory in the parent process allocated for fork_data
> fixed memory leak detected by ASAN when running FIO jobs from within parent process

- init.c
- freeing job_sections array of strings upon freeing each its item in init.c
> freeing job_sections array to avoid wasting memory and possible indirect memory leak

- backend.c
- fixed memory leaking in the parent process detected by ASAN
> fixed memory leaking in the parent process detected by ASAN

- configure
- configure script refactoring, tabs are replaced by spaces in the help page of configure script
> Substituted tabs by spaces in help page of configure script

- filesetup.c
- cleared allocation of td->files when duplicating files
- call 'assert', before iterating over original thread_data, that prevents possible segmentation fault when duplicating files
> Improvements in dup_files function

- configure
- possible enabling ASAN for the compiler when calling 'configure' srript using '--enable-asan' option
> opportunity for a user to compile with ASAN by giving the option to the configure script

- Makefile
With a vanilla build t/fuzz/parse_ini will segfault because the symbol
FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION is not defined. If the symbol
FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION is defined, fio won't tear down
shared memory on program termination. Not tearing down shared memory is
necessary for t/fuzz/parse_ini to work correctly.
Don't build t/fuzz/parse_ini unless CFLAGS contains
-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION.
Signed-off-by: Vincent Fu <vincent.fu@samsung.com>
> fuzz: avoid building t/fuzz/parse_ini by default

- fio.h
We have 16 engine flags and an 18-bit shift, so cast engine flags to
unsigned long long before shifting to avoid dropping
FIO_ASYNCIO_SYNC_TRIM and FIO_NO_OFFLOAD.
Also make thread_data::flags unsigned long long to ensure it fits all
flags even when longs are 32 bit, and fix TD_ENG_FLAG_MASK.
Signed-off-by: Alberto Faria <afaria@redhat.com>
> Properly encode engine flags in thread_data::flags

- CITATION.cff
Hi there this is a github repo specific enhancement.
Have been referencing FIO recently and was generating bibtex for this repo. I came across a Github way of adding a CITATION.cff file which adds a nice little menu button for others to easy cite it in APA/Bibtex. Thought I may add it, see added file/pictures. More information on the CITATION.cff feature here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files (unfortunately APA only available currently but BibTeX was what I was after).
Thanks
Jono
> Quick cite this repository - APA/BibTeX

- compiler/compiler.h
gcc-4.9.3 doesn't recognize `__has_attribute(__fallthrough__)` and reports
the following error.
```
CC crc/crc32c-arm64.o
In file included from crc/../os/../file.h:5:0,
from crc/../os/os-linux.h:32,
from crc/../os/os.h:39,
from crc/crc32c-arm64.c:2:
crc/../os/../compiler/compiler.h:74:20: error: missing binary operator before token "("
Makefile:501: recipe for target 'crc/crc32c-arm64.o' failed
make: *** [crc/crc32c-arm64.o] Error 1
```
Signed-off-by: Chung-Chiang Cheng <cccheng@synology.com>
> Fix compile error of GCC 4

- stat.c
stat: When printing job stats with status-interval, don't keep adding values to
the total runtime if the jobs are already finished. This should fix the printing
of the intermediate runtime/average BW etc.
Signed-off-by: Kozlowski Mateusz <mateusz.kozlowski@intel.com>
> Handle finished jobs when using status-interval

- backend.c
- ioengines.c
backend.c: release memory occupied by the parent process for options
ioengines.c: free_ioengine entry point is protected by 'assert' call
upon td and td->io_ops
> fixed possible and actual memory leaks

- eta.c
- server.c
- stat.c
Launch fio built with ASAN enabled, for example, by this way:
```
./fio --max-jobs=4 --output=fio-output.json --output-format=json+ --filename=fio_jsonplus_clat2csv.test --ioengine=libaio --time_based --runtime=3s --size=1M --slat_percentiles=1 --clat_percentiles=1 --lat_percentiles=1 --thread=1 --name=test1 --rw=randrw --name=test2 --rw=read --name=test3 --rw=write --thread=1
```
Borrowed from one tests the project has got
We can see many memory leaks, in particular:
```
Direct leak of 573 byte(s) in 3 object(s) allocated from:
#0 0x345e0d in malloc (/home/dpronin/Development/workspace/fio/fio+0x345e0d)
#1 0x414499 in get_jobs_eta /home/dpronin/Development/workspace/fio/eta.c:690:7
```
This PR fixes this leak
> fixed jobs eta memory leak

- json.h
- t/run-fio-tests.py
fixed memory leak produced by not freed string given by 'strdup' in
'json_object_add_value_string' function. Just removed 'strdup' and made
string in 'json_value' as immutable
> fixed bunch of memory leaks in json constructor

- HOWTO.rst
- backend.c
- cconv.c
- dedupe.c
- dedupe.h
- examples/dedupe-global.fio
- fio.1
- init.c
- options.c
- server.h
- thread_options.h
Introducing support for generation of dedup buffers across jobs. 
The dedup buffers are spread evenly
between the jobs that enabled the dedupe_global option
Note only dedupe_mode=working_set is supported.
Note compression is supported with the global dedup enabled
Signed-off-by: Bar David <bardavvid@gmail.com>
> Global dedup

- README.rst
Fedora's https://apps.fedoraproject.org/ bit the dust a while back, changed link to the closest working alternative.
> README: Update Fedora pkg URL

- engines/pmemblk.c
logic issue,if read success and return 0, then pmemblk_write called as well:
if (io_u->ddir == DDIR_READ &&
0 != pmemblk_read(pmb->pmb_pool, buf, off)) {
io_u->error = errno;
break;
} else if (0 != pmemblk_write(pmb->pmb_pool, buf, off)) {
io_u->error = errno;
break;
}
> pmemblk.c: fix one logic bug - read always with write

- HOWTO.rst
- engines/rados.c
- examples/rados.fio
- fio.1
Specifies the configuration path of ceph cluster on rados test, so
conf file does not have to be /etc/ceph/ceph.conf.
Signed-off-by: Mingyuan Liang <liangmingyuan@baidu.com>
> engines/ceph: add option for setting config file path

- blktrace.c
In the very unlikely case that the trace was taken from a device with
major and minor zeroes, the cache will wrongly hit the first time. We
are hitting this problem when trying to replay generated traces with
major and minor zeroes. Initializing with ~0U fixes this problem.
Signed-off-by: Luis Useche useche@gmail.com
> Init file_cache to invalid (maj, min)

- lib/rand.c
This reduces the number of source lines and the code size.
For example, when compiling with GCC 12.1 (-O3 -march=skylake), the
resulting assembly shrinks from 33 to 27 instructions and the number of
jump instructions is reduced from 4 to 3.
NB: GCC is able to eliminate the memcpy() call.
NB: Even if a compiler doesn't eliminate the memcpy() call, it's very
unlikely to ever get called since the buffer sizes are expected to be
powers of two [greater than 8], usually.
---
Motivation: On a somewhat underpowered CPU I noticed that fio was CPU bound (when running with `refill_buffers`) and profiling showed that most of the time was spent in `__fill_random_buf()`.
I thus optimized it a bit and observed an improvement of 20 % or so in the fio throughput.
See also: https://godbolt.org/z/57fGGYqsM
> Simplify and optimize __fill_random_buf

- server.c
Signed-off-by: Ulrich Weigand <ulrich.weigand@de.ibm.com>
Signed-off-by: Tuan Hoang <tuan.hoang1@ibm.com>
> server: only do cpu_to_le64() on io_sample_data member if iolog is histogram

- client.c
In the case of histogram iolog, the union io_sample_data member is a
pointer of struct io_u_plat_entry, while in the case of normal iolog, it
is an uint64_t. Thus only need to do the byteswap in case it is an
uint64_t.
This has been done similarly in server code.
Signed-off-by: Ulrich Weigand <ulrich.weigand@de.ibm.com>
Signed-off-by: Tuan Hoang <tuan.hoang1@ibm.com>
> client: only do le64_to_cpu() on io_sample_data member if iolog is histogram

- engines/http.c
In http.c:fio_http_queue function, when the user specifies rw=write and if curl_easy_perform fails then the control reaches line 565 and incorrectly prints: "WARNING: Only DDIR_READ/DDIR_WRITE/DDIR_TRIM are supported!".
Fix to this consists in moving statement: "goto err" at the end of the block as already has been done for trim/read blocks.
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>
> Fixed misplaced goto in http.c

- backend.c
- file.h
- filesetup.c
Proposal to fix axboe/fio#1424
I added some changes to perform file creation/extension when running with create_serialize=0 and nr_files=1.  setup_files() will still be done in parallel after the threads are kicked off later, but some early, single-threaded file creation will be done now.  This will put things in a good enough state that steup_files() should not need to unlink and create new files, thus avoiding the original issue.
I did find that there is still an issue when using --fallocate=none as an argument.  This results in a file of size 0, and setup_files() will still later try to perform the setup in parallel.  Using fallocate=native or fallocate=truncate both appear to be viable and desirable alternatives to fallocate=none.  
The combination of these changes and …
> Fix multithread setup issues when operating on a single shared file

- configure
- lib/rand.c
The __fill_random_buf fills a buffer using the random 8byte integer for
write operation. But, this mechanism is depend on the CPU performance
and could not reach the max performance on the PCIe Gen5 devices.
I have tested 128KB single worker sequential write on PCIe Gen5 NVMe,
but it cannot reach write throughput 6.0GB/s.
So, I have reviewed the __fill_random_buf and focused the multiplier
dependency to generate the random number. So, I have changed
__fill_random_buf using the multiple-random-seed to reduce the
dependencies bewteen generating and assinging in the small data
filling loop.
I'll attach detail analysis result in the PR of this branch.
Signed-off-by: Sungup Moon <sungup.moon@samsung.com>
> lib/rand: Enhance __fill_random_buf using the multiple random seed

- HOWTO.rst
- engines/http.c
- examples/http-s3-crypto.fio
- examples/http-s3-storage-class.fio
- fio.1
Amazon S3 offers a range of storage classes that you can choose from
based on the data access, resiliency, and cost requirements of your
workloads. (https://aws.amazon.com/s3/storage-classes/)
For example, we have **STANDARD** storage class to test normal
workload, and have **COLD** storage class to test the workload
with gzip compression. It is convenient to select which
storage class to access for different kinds data.
Server-side encryption is about protecting data at rest.
(https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerSideEncryptionCustomerKeys.html)
When we want to test server-side encryption, we need to specify
server-side encryption with customer-provided encryption keys (SSE-C).
The two option **http_s3_sse_customer_key** and
**http_s3_sse_customer_algorithm** is …
> engines/http: Add s3 crypto and storage class options

- os/os-android.h
This patch enables the --cpumask=, --cpus_allowed= and
--cpus_allowed_policy= fio options.
> Enable CPU affinity support on Android

- t/io_uring.c
__init_rand64 takes 64bit value and srand48 takes unsigned 32bit value,
pthread_t is opaque type and some libcs ( e.g. musl ) do not define them
in plain old data types and ends up with errors
| t/io_uring.c:809:32: error: incompatible pointer to integer conversion passing 'pthread_t' (aka 'struct __pthread *') to parameter of type 'uint64_t' (aka 'unsigned long') [-Wint-conver
sion]
|         __init_rand64(&s->rand_state, pthread_self());
|                                       ^~~~~~~~~~~~~~
Signed-off-by: Khem Raj <raj.khem@gmail.com>
1. First line is a commit title, a descriptive one-liner for the change
2. Empty second line
3. Commit message body that explains why the change is useful. Break lines that
aren't …
> io_uring: dereference pthread_t value from pthread_self

- iolog.c
Set the file open mode to be binary instead of text when dealing with
compressed log files. This fixes log compression storage not working on
windows, and lets the test added in PR
https://github.com/axboe/fio/pull/1458
pass on windows.
CONFIRMED
1. First line is a commit title, a descriptive one-liner for the change
2. Empty second line
3. Commit message body that explains why the change is useful. Break lines that
aren't something like a URL at 72-74 chars.
4. Empty line
5. Signed-off-by: Real Name <real@email.com>
> Fix log compression storage on windows

- HOWTO.rst
- fio.1
It does not take an argument, but operates on the job files and other arguments given on the command line.
Refs https://github.com/scop/bash-completion/pull/777#issuecomment-1236056555
> doc: fix --showcmd usage

- configure
configure's libcufile probe now requires -ldl passed to the linker.
Signed-off-by: Brian T. Smith <bsmith@systemfabricworks.com>
> fix configure probe for libcufile

- configure
- engines/libcufile.c
libcufile: use generic_get_file_size
In libcufile ioengine_ops, set get_file_size to generic_get_file_size.
Fixes #1213.
Signed-off-by: Brian T. Smith <bsmith@systemfabricworks.com>
> Fix for Issue 1213

- fio.1
Spelling and markup fixes for man 1 fio reported by lintian (a Debian package linter) while reviewing the package.
> Lintian manpage fixes

- iolog.c
Add -replay_skip support for fio-generated I/O logs
`-replay_skip` is an existing option to specify classes of I/Os to skip
(read, write, etc..) when replaying I/Os via the `-read_iolog` option.
The code currently only implements `-replay_skip` for blktrace I/O logs.
This pull request adds `-replay_skip` support for logs generated by fio
via the `-write_iolog` feature.
> Add -replay_skip support for fio I/O logs (currently only supported for blktrace logs)

- io_u.c
Profiling revealed thread_main() is spending 50% of its time in calls to utime_since_now() from rate_ddir(). This call is only necessary if the user specified a rate option for the job. A conditional was added to avoid the call if !should_check_rate(). See this link for details and profiling data:
https://github.com/axboe/fio/issues/1501#issuecomment-1418327049
> Improve IOPs 50% by avoiding clock sampling when rate options not used

- rate-submit.c
Segmentation fault when log_io_u() attempts to write an entry to a user-specified write_iolog file, if the I/O is issued from an offload thread created by io_submit_mode=offload. Call path:
rate-submit.c::io_workqueue_fn() -> td_io_queue() -> log_io_u(td, io_u)
The log file handle in thread_data->iolog_f opened by init_iolog() is not being copied to the offload thread's private copy of thread_data, causing a NULL deference when fprintf() is called to write to the log file.
Fix is to copy the main thread's td->iolog_f to the offload thread's td at creation time. Seems a bit disjointed to be copying individual fields between these two structures on an as-needed basis rather than having a mechanism to replicate the entire structure, or at least replicating the I/O submission specific fields …
> SIGSEGV / Exit 139 when write_iolog used with io_submit_mode=offload

- backend.c
The user is warned if iodepth > 1 when using a synchronous I/O engine, since the engine can only submit one I/O at a time. This warning is not accounting for the case of the user enabling I/O submission offload threads via io_submit_mode=offload. Modified the warning conditional to suppress the warning when this is the case.
> Suppress sync engine QD > 1 warning if io_submit_mode is offload

- backend.c
- fio.h
Verify fails with "bad header rand_seed" when multiple iterations of do_io() execute (time_based=1 or loops>0), with verify enabled and randrepeat=0
The root cause is do_verify() resetting the verify seed back to the job-init value, which works for verification of the first iteration of do_io() but fails for subsequent iterations because the seed is left in its post-do_io() state after the first do_verify(), which means different rand values for the second iteration of do_io() yet the second iteration of do_verify() will revert back again to the job-init seed value.
The fix is to revert the verify seed for randrepeat=0 back to ts state when do_io() last ran rather than to its job-init value. That will allow do_verify() to use the correct seed for each iteration while still retaining a …
> Bad header rand_seed with time_based or loops with randrepeat=0 verify

- backend.c
- io_u.c
- io_u.h
On configurations that can cause I/Os to be internally requeued from FIO_Q_BUSY such as '--iodepth_batch_complete_max', and the workload has verify enabled, the subsequent verification of the data fails with a bad verify rand_seed because the pattern for the I/O is generated twice for the same I/O, causing the seed to become out of sync when the verify is later performed. The seed is generate twice because do_io() handles the I/O twice, first when it originates the I/O and again when it later gets the same I/O back from get_io_u() after it's is pulled from the requeue list, which is where the first submission landed due to the workload reaching '--iodepth_batch_complete_max'.
The fix is for do_io() to track when it has generated the verify pattern for an I/O via a new io_u flag …
> FIx "verify bad_hdr rand_seed" for requeued I/Os

- io_u.h
- ioengines.c
- rate-submit.c
Assertion in ioengines.c::td_io_queue() fails for pthread_mutex_unlock() on overlap_check mutex when serialize_overlap=1, io_submit_mode=offload, and verify=<any> are used together.
backend.c::fio_io_sync() invokes td_io_queue(), which expects the caller to have ownership of the overlap_check mutex when serialize_overlap and offloading are configured, as part of the overlap-check interlock with IO_U_F_FLIGHT. The mutex is not acquired for this path because it's not an I/O requiring an overlap check.
The fix is to refine the conditional that triggers td_io_queue() to release the overlap_check mutex. Rather than using broad config options, the conditional now uses a new io_u flag named IO_U_F_OVERLAP_LOCK, which is only set for the offload worker thread path that acquires the mutex.
Link: …
> ioengines.c:346: td_io_queue: Assertion `res == 0' failed

- HOWTO.rst
- fio.1
I realize this is highly subjective but I think the description of the runtime parameter could be made a bit more precise. I misinterpreted its meaning after reading the doc and only learned of my mistake by trial and error using fio.  Either I'm just slow or the description could use just a little more precision :)
> Clarify documentation for runtime parameter

- tools/fiologparser.py
The logging format updates documented in 1a953d97 were never propagated to fiologparser.py, which since then has been failing with a ValueError exception.
This commit explicitly limits fiologparser.py to only reading the first 2 columns in the log file, because they are the only columns used.
This is similar to issue #928.
> fix fiologparser.py to work with new logging format

- eta.c
Segmentation fault occurs when aggregate bandwidth logging is enabled (--bandwidth-log) and numjobs is an even multiple of 8. Fault occurs because logic is using the terminating value of struct thread_data *td from the most recent for_each_td(). This bug was caught by the refactoring of for_each_td().
Link: https://github.com/axboe/fio/issues/1534
> Fix --bandwidth-log segmentation fault when numjobs even multiple of 8

- backend.c
- dedupe.c
- engines/libblkio.c
- eta.c
- fio.h
- init.c
- iolog.c
- libfio.c
- rate-submit.c
- stat.c
- steadystate.c
- verify.c
- zbd.c
I recently introduced a bug caused by reusing a struct thread_data *td after the end of a for_each_td() loop construct.
Link: https://github.com/axboe/fio/pull/1521#issuecomment-1448591102
To prevent others from making this same mistake, this commit refactors for_each_td() so that both the struct thread_data * and the loop index variable are placed inside their own scope for the loop. This will cause any reference to those variables outside the for_each_td() to produce an undeclared identifier error, provided the outer scope doesn't already reuse those same variable names for other code within the routine (which is fine because the scopes are separate).
Because C/C++ doesn't let you declare two different variable types within the scope of a for() loop initializer, creating a scope for …
> Refactor for_each_td() to catch inappropriate td ptr reuse

- engines/io_uring.c
- engines/nvme.c
- engines/nvme.h
- fdp.c
- stat.c
This series has 2 commits:
1. For fdp remove the usage of expensive modulo operation as the same can be achieved with addition and wrapping around available reclaim unit handles.
2. Add support for trim operation to the io_uring_cmd ioengine. Print ZBD zone reset stats for trim operation.
> fdp cleanup and trim support for io_uring_cmd

- fio.h
- libfio.c
Prevent I/O bursts after `ramptime` due to thinktime.
Each thread generates a certain amount of I/O requests, configured by `thinktime_blocks`.
When `ramptime` ends, `thinktime_blocks` can't control I/O. Because `thinktime_blocks` are not reinitialized after `ramptime`.
I fixed it by reinitializing `last_thinktime` and `last_thinktime_blocks` when `ramptime` ended.
Details with figures below:
(cmd: `fio --filename=/dev/nvme0n1 --rw=read --bs=128k --iodepth=256 --size=100% --name=thinktime_test --direct=1 --ramp_time=30 --ioengine=libaio --runtime=20 --time_based --thinktime=500ms --thinktime_blocks=1000 --write_iops_log=/root/fiofix/fixed_fio --log_avg_msec=1000`)
After debug, iops is being controlled by thinktime_blocks.
> thinktime: Fix missing re-init thinktime when using ramptime

- engines/libaio.c
If the io_getevents system call is interrupted, it can succeed while returning less than the min_nr requested events. If this occurs during the final reaping of events, libaio will call io_getevents again wtih the same minimum events argument. Since some of the events have already been reaped, this results in a hang. To fix this, update the arguments for io_getevents based on the previously seen events.
> engines/libaio: fix io_getevents min/max events arguments

- arch/arch-loongarch64.h
- arch/arch.h
- configure
- libfio.c
- os/os-linux-syscall.h
Hi,There are many warnings when compiling on the LoongArch64 architecture, for example：
> crc/../arch/arch.h:101:2: warning: #warning "Unknown architecture, attempting to use generic model." [-Wcpp]
101 | #warning "Unknown architecture, attempting to use generic model."
|  ^~~~~~~
In file included from crc/../os/os-linux.h:40,
from crc/../os/os.h:37,
from crc/crc32c-arm64.c:2:
crc/../os/./os-linux-syscall.h:274:2: warning: #warning "Unknown architecture" [-Wcpp]
274 | #warning "Unknown architecture"
So I submitted this pr to add LoongArch64 port.
About LoongArch:
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.
Documentations:https://loongson.github.io/LoongArch-Documentation/README-EN.html
thanks.
> Add LoongArch64 support

- backend.c
- helper_thread.c
- io_u.c
- ioengines.c
- rate-submit.c
- server.c
- t/read-to-pipe-async.c
- zbd.c
Observation before changes: if CFLAGS is given with -DNDEBUG we will see that everything that is checked within `assert` call is discarded since `assert` is a macro that turns into nothing if NDEBUG is given while compilation
I sophisticated using these unused variables by dummy casting them to void
> fix warnings if NDEBUG is enabled

- engines/io_uring.c
In io_uring sqpoll mode, when kernel side thread has not yet read  the sqring before second fio_ioring_commit() called, the  sq_ring.head will remain the same. The second 
fio_ioring_commit() will initialize the wrong io_u's issue_time.  The old(in head) io_u‘s issue_time will to be initialized twice and  new(in tail - 1) io_u's issue_time will not to be initialized. This problem will cause clat is weird, sometimes larger than lat.
Situation:
1. fio_ioring_queue(td, io_u_a) // head -> io_u_a;  tail -> io_u_a + 1
2. fio_ioring_commit(td)   // initial io_u_a.issue_time
3. fio_ioring_queue(td, io_u_b) // head -> io_u_a; tail -> io_u_b + 1
4. fio_ioring_commit(td)  // initial io_u_a.issue_time again
5. kernel thread read sq_ring, // head += 2
io_u_b.issue_time is never initilized.
> fix: io_uring sqpoll issue_time empty when kernel not yet read sq

- diskutil.h
diskutil.h requires 3 more headers to fulfill several types therein  without having to rely on headers hopefully included before this one
> diskutil.h: fix missing headers wanted by the header

- helper_thread.h
- missing headers should be included at the places where they are certainly used, so include <stdbool.h>
- helper_thread_create() function requires two structures to be declared, so declare in advance `struct fio_sem` and `struct sk_out`
> helper_thread.h: fix missing header and types forward declaration

- backend.c
- cairo_text_helpers.c
- cairo_text_helpers.h
- goptions.h
- ioengines.c
- log.c
- options.c
for non-threaded mode: since thread_data::eo is a pointer within shared  memory between the topmost fio parent process and its children let the  fio parent process set the pointer to NULL as just it frees its copy of  'eo' as memory previously allocated by means of 'malloc' meaning that  each child and the parent process itself must free it
for threaded mode we leave it as it has always been
also we do not need to check td->io_ops for being able to free td->eo in
fio_options_free()
This PR should fix double-free problem described in [this issue](https://github.com/axboe/fio/issues/1598) and also should fix issue described in [this PR](https://github.com/axboe/fio/pull/1581)
> correctly free thread_data options at the topmost parent process

- engines/io_uring.c
motivation here is that we do not have here any explicit READ dependency
on atomic load because actually we just need in these places only
operation to perform atomically without any explicit barriers given by
memory model
> io_uring engine: 'atomic_load_relaxed' instead of 'atomic_load_acquire'

- iolog.c
When do timestamp replay with high qd it will only reap the completed commands when the qd reach the max iodepth, the commands probably are finished long ago before command completion handling.
Fix is to use io_u_queued_complete instead of just usec_sleep in iolog_delay
Signed-off-by: Kookoo Gu <Zhimin.Gu@solidigm.com>
> iolog.c: fix inaccurate clat when replay trace

- options.c
Previously this was parsed by just doing atoi(<nr>). This returns 0 or has undefined behavior in error cases.
Silently getting a 0 for nr is not great. In fact, 0 (or less) should likely not be allowed for nr; while the code handles it, the effective result is that the randomness is gone - all I/O becomes sequential. It makes sense to prohibit 0 as an nr value in the random case.
We leverage str_to_decimal to do our parsing instead of atoi. It isn't perfect, but it is a lot more resilient than atoi, and used in other similar places. We can then return an error when parsing fails, and also return an error when the parsed numeric value is outside of the ranges that can be stored in the unsigned int used for nr, along with when nr is 0.
Fixes #1622
Signed-off-by: Nick Neumann …
> Add basic error checking to parsing nr from rw=randrw:<nr>, etc

- HOWTO.rst
- backend.c
- cconv.c
- client.c
- fio.1
- fio.h
- fio_time.h
- libfio.c
- options.c
- rate-submit.c
- server.c
- stat.c
- stat.h
- thread_options.h
- time.c
Add a new key in the json per-job output, job_start, that records the job start time obtained via a call to clock_gettime using the clock_id specified by the new job_start_clock_id option. This allows times of fio jobs and log entries to be compared/ordered against each other and against other system events recorded against the same clock_id.
Also make log_unix_epoch an official alias of log_alternate_epoch, instead of maintaining both redundant options.
Add a note to the documentation for group_reporting about how there are several per-job values for which only the first job's value is recorded in the json output format when group_reporting is enabled.
Fixes #1544
Signed-off-by: Nick Neumann nick@pcpartpicker.com
> Record job start time to fix time pain points

- HOWTO.rst
- fio.1
When run in client mode, fio does not pass any job options specified on the command line to the fio server. When run in client mode, all job options must be specified via local or remote job files. Update the docs to indicate this to avoid end-user confusion.
Fixes #1629
Signed-off-by: Nick Neumann nick@pcpartpicker.com
> Update docs to clarify how to pass job options in client mode

- verify.c
We offset `buf` by `header_size` for pattern verification. Add `header_size` to the mismatched `buf` offset to get the correct block offset value.
> verify: Fix the bad pattern block offset value

- diskutil.c
Linux prints [1] some of the values reported in block device's `stat` sysfs file as 32-bit unsigned integers. fio interprets them as 64-bit integers when reading that sysfs file and performs further arithmetics on them in 64-bits. If the reported value overflows during fio run, a huge bogus value is reported in the "disk utilization" block instead.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/block/genhd.c#n962
> Handle 32-bit overflows in disk utilization stats

- io_ddir.h
- io_u.c
- zbd.c
fix assert failed when timeout during call rate_ddir
Adding DDIR_TIMEOUT in enum `fio_ddir`, and `rate_ddir` returns it when fio timeouts. `set_io_u_file` will directly break out of the loop, and `fill_io_u` won't be called again, which causes assert to fail in `rate_ddir`, because td->rwmix_ddir is DDIR_INVAL.
Signed-off-by: QingSong Zhu <zhuqingsong.0909@bytedance.com>
> fix assert failed when timeout during call rate_ddir

- configure
- helper_thread.c
fix typo in helper_thread.c and add sigmask var to configure to detect the existence of pthread_sigmask.
Compiling the code with the typo fix of "#ifdef CONFIG_PTHREAD_SIGMASK" will show that ret is unknown, hence, we are adding the line "int ret;". This fix of typo will fix some other bugs I've encountered.
In case of a msys2, configure script handles it, it triggers the same warning that is in the build failure to fail to detect pthread_sigmask when it is defined to be a noop.
Signed-off-by: Shai Levy [shailevy23@gmail.com](mailto:shailevy23@gmail.com).
> fix typo in helper_thread.c and add sigmask var to configure script in order to handle msys2.

- arch/arch-riscv64.h
`rdcycle` pseudo-instruction accesses the "cycle CSR" which holds the real count of CPU core clock cycles [1]. As this leaves room for side-channel attacks, access to this register from userland might be forbidden by the kernel, which results in a SIGILL [2].
Anyhow, it seems that the actual usage of the `get_cpu_clock` function in fio is about getting a wall-clock rather than the actual CPU core clock (for instance, x86 uses `rdtsc`), so this is technically a bug. The "time CSR" is the proper register to track time on riscv64. Also, the "time CSR" is more likely to be available from userspace and not cause a crash.
[1] RISC-V ISA Section 10.1: https://github.com/riscv/riscv-isa-manual/releases/download/Ratified-IMAFDQC/riscv-spec-20191213.pdf
[2] …
> riscv64: get clock from `rdtime` instead of `rdcycle`

- HOWTO.rst
- configure
- fio.1
This merge request contains various spelling fixes to fio manpage and HOWTO.
Most of them have been reported by Debian's Lintian tool.
> Various spelling fixes

- engines/nfs.c
`ioengine` from `nfs` (internal) engine is incorrectly exported thus overriding its value in constructor callbacks of other external engines, that are used for registering engine for listing with `--enghelp`.
Because flist is unsafe to double adding it also making `engine_list` to become corrupt and causing infinite loop or abnormal list termination when printing engine list.
Issue: https://github.com/axboe/fio/issues/1655
Fixes: 9326926b ("NFS engine")
---
It seems that `ioengine` for internal engines should not be exported and should be always `static`.
The change is tested downstream on ALT Linux.
> nfs: Fix incorrect engine registering for '--enghelp' list

- HOWTO.rst
- configure
- crc/crct10dif_common.c
- fio.1
isa-l provides fast implementation for various polynomials.
This will be only used for end to end data protection, and has a significant impact on performance.
For ISA_L please check: https://github.com/intel/isa-l
> crct10: use isa-l for crc if available

- engines/xnvme.c
This changes how the xNVMe fio io-engine consumes the xNVMe library by only including the library-entry header "libxnvme.h".
From version 0.7.0 the xNVMe API headers are refactored to drop header guards on the individual headers and abide by the idiom of "headers must not include other headers".
The exception is the library-entry header "libxnvme.h". The library-entry-header includes all headers provided with xNVMe, which is a convenient approach to consuming the library. One where, in case the API namespace grows or shrinks, then the xNVMe fio io-engine need not change how it includes xNVMe.
However, since fio has consumed the main-entry header and individual headers, xNVMe has held back on removing the guards on _nvm, _zns, and _spec to avoid breaking the xNVMe fio engine. They will …
> engines/xnvme: only include entry-header ('libxnvme.h')

- ioengines.c
Linux kernel commit 7b12e49669c9 ("fs: remove fs.f_write_hint") removed F_SET_FILE_RW_HINT support from the Linux kernel. Hence fall back to F_SET_RW_HINT if F_SET_FILE_RW_HINT is not supported.
> Fall back to F_SET_RW_HINT if F_SET_FILE_RW_HINT is not supported

- engines/http.c
Found by Red Hat's OpenScanHub:
fio-3.35/engines/http.c:253: leaked_storage: Variable r going out of scope leaks the storage it points to.
Signed-off-by: Pavel Reichl <preichl@redhat.com>
> engines/http: Fix memory leak

- engines/http.c
- engines/rdma.c
- server.c
Following issues were found by Red Hat's OpenScanHub:
fio-3.35/engines/rdma.c:279:3: warning[deadcode.DeadStores]:
Value stored to 'ret' is never read
fio-3.35/server.c:1884:3: warning[deadcode.DeadStores]:
Value stored to 'extended_buf_wp' is never read
fio-3.35/engines/http.c:642: var_tested_neg:
Assigning: "r" = a negative value.
fio-3.35/engines/http.c:714: assign: Assigning: "io_u->error" = "r". fio-3.35/engines/http.c:715: negative_returns: "io_u->error" is passed
to a parameter that cannot be negative.
I suggest changing the data type of io_u->error from uint to int since it appears that negative values are being assigned to it.
> Fix a few issues found by scanner

- HOWTO.rst
Use tabs consistently for the paragraphs describing the group_reporting option. Also, make sure that there is no space between ":option:" and "`group_reporting`".
----
Here's a screenshot of how the docs are currently rendered incorrectly:
> doc: group_reporting: Fix indentation and syntax

- iolog.c
Fix the two Null pointer dereferences issue reported by Coverity scan
Null pointer dereferences  (FORWARD_NULL)
Dereferencing null pointer "l->td"
Null pointer dereferences  (REVERSE_INULL)
Null-checking "p->td" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
> fix reported defect from coverity scan

- iolog.c
iolog: fix disk stats issue
In the iolog replay scenario, the disk util in the td structure is
not initialized, resulting in the disk stats not being correctly
updated.
Fixes: https://github.com/axboe/fio/issues/1735
Signed-off-by: Yong Gang <yygcode@gmail.com>
> iolog: fix disk stats issue

- HOWTO.rst
- fio.1
This way people would have an easier time discovering this command-line option, see https://github.com/axboe/fio/issues/1739.
> docs: use "delete" term instead of "unlink", which is less common

- io_u.c
- ioengines.c
FIO with fsync option issues more DDIR_SYNC commands than expected
When fsync option is used, the number of flush (or DDIR_SYNC) commands
issued is more than the expected number of flush commands.
To elaborate:
- In the fio config file, consider fsync=1
1. FIO issues 1 write command
2. After write completes, FIO sets last_was_sync variable to false
3. FIO issues 1 flush command
4. FIO keeps issuing flush commands since last_was_sync is still false
and this causes more flush commands to be issued than expected
5. last_was_sync is set to true after the flush command completes
- The above steps repeats until the workload is completed.
Instead of setting last_was_sync to true after flush command is completed
and setting last_was_sync to false after write command is completed,
set …
> FIO with fsync option issues more DDIR_SYNC commands than expected

- HOWTO.rst
- cconv.c
- dataplacement.c
- dataplacement.h
- file.h
- fio.1
- options.c
- server.h
- t/nvmept_fdp.py
- thread_options.h
Add a new placement id selection method called scheme. It allows
users to assign a placement ID (index) depending on the offset range.
The strategy of the scheme is specified in the file by user and
is applicable using the option dp_scheme.
Signed-off-by: Hyunwoo Park <dshw.park@samsung.com>
- 302/303: invalid options tests
- 400/401: check whether fdp scheme works properly
Signed-off-by: Hyunwoo Park <dshw.park@samsung.com>
> fdp: support scheme placement id selection

- engines/io_uring.c
- options.c
The 'io_uring_cmd' ioengine returns the status code type and status code of
NVMe CQE [27:17] to io_u in case of errors.  The first patch fixes the CQE
value being returned as negative since it's not an errno.  The next one is a
trivial patch to support hexadecimal format to 'ignore_error' option to mask
values such as the status type and status code in a more comfortable way.
> io_uring: Fix error status of cqe

- iolog.c
- t/nvmept_fdp.py
Add initialization and dataplacement logic to enable
dataplacement(fdp) while fio replays I/Os with read_iolog.
Signed-off-by: Hyunwoo Park <dshw.park@samsung.com>
A test(402) checks whether dataplacement(fdp) works fine while replaying iologs
Signed-off-by: Hyunwoo Park <dshw.park@samsung.com>
> fio: enable dataplacement(fdp) while replaying I/Os

- iolog.c
CID 494151: Error handling issues (NEGATIVE_RETURNS) @ io_u.c:1877 in get_io_u()
This patch removes negative returns from dp_init() to ensure
its value can be properly consumed by td_verror()
Signed-off-by: Hyunwoo Park <dshw.park@samsung.com>
CID 494150: Null pointer dereferences (FORWARD_NULL) @ iolog.c:148 in ipo_special()
This patch removes the possibility of null pointer dereferencing(io_u->file)
throughout the call stack of get_io_u() → read_iolog_get() → dp_fill_dspec_data()
Signed-off-by: Hyunwoo Park <dshw.park@samsung.com>
> iolog, dataplacement: fix coverity scan defect

- HOWTO.rst
- engines/io_uring.c
- engines/nvme.c
- engines/nvme.h
- fio.1
Add a new option 'write_mode' to support additional optional Write
command family such as Write Uncorrectable and Write Zeroes in NVMe.
Since we have io_uring_cmd ioengine where we can define the actual
opcode of the command, this option will be used to test NVMe device with
various combination of Write command types.
'write_mode' option can be given either 'write', 'uncor', 'zeroes' or
'verify'.  'write' is for normal Write command which is by default,
'uncor' is for Write Uncorrectable, 'zeroes' for Write Zeroes and 'verify'
for Verify command  This should be used with DDIR_WRITE ddir.
This patch updates command's opcode in fio_ioring_init() to avoid
branches in the I/O hottest path giving opcode value to the
fio_nvme_uring_cmd_prep() as an argument.
> io_uring: Add 'write_mode' option for optional cmds

- engines/nfs.c
Fio would fail to stop jobs when set io mode other than write by using nfs engine. This fix can make sure randwrite works correctly since both write and randwrite will create file first and then start IO.
Note: for nfs engine, other IO modes which include read will require user to have the file ready before test start. If we want fio to setup and extend the file before job start, that would involve more code changes. The fix here only make randwrite would behave the same as write, and this should match what user should expect.
> Fix issue when start randwrite by using nfs engine

- configure
- engines/e4defrag.c
- os/os-qnx.h
- os/os.h
Add support QNX OS platform
To  mainline those changes for better maintenance.
Compile command: QNX SDP7.1 example
./configure --cc=aarch64-unknown-nto-qnx7.1.0-gcc --disable-shm; make
Basic file read and write test with ioengine=sync is verified.
Signed-off-by: Huang weiliang <weller.huang@us.bosch.com>
> Support QNX OS platform

- dataplacement.c
- dataplacement.h
- ioengines.h
This series has 3 patches
1. Removing FDP_MAX_RUHS, as now we are fetching all the ruhs reported by the device, and then parsing the ones requested as per the placement ID indices.
2. log_info to log_err for all the error messages.
3. Incrementing FIO_IOOPS_VERSION, for any external ioengine which may be using fdp_fetch_ruhs.
> Small fdp fixes

- HOWTO.rst
- examples/http-s3.fio
- fio.1
In fio.1 and HOWTO.rst:
* http_host: add details on vHost- vs Path-style hostname differences
* filename: add details on bucket prefix for Path-style hostname In examples/http-s3.fio:
* add comments at the top to clarify vHost vs Path S3 and change the hostname in existing example to disambiguate two scenarios
This is a documentation & example only change for issue #1797. 
Hopefully the commit message is formatted according to your requirements. Feel free to make any edits you wish. Thank you.
> Improve http_host, filename in docs and example/http-s3.fio

- engines/io_uring.c
- engines/librpma_fio.c
- engines/librpma_fio.h
- engines/sg.c
- io_u.c
- ioengines.h
Background
- fio normally prints out the strerr and errno value when facing errors.  In case of io_uring_cmd ioengine with --cmd_type=nvme, io_u->error represents the CQ entry status code type and status code which should be parsed as a NVMe error value rather than errno.
In io_u error failure condition, it prints out parsed CQ entry error status values with SCT(Status Code Type) and SC(Status Code).  The print will be like the following example:
fio: io_uring_cmd: /dev/ng0n1: cq entry status (sct=0x00; sc=0x04)
If --cmd_type!=nvme, it prints out generic status code like below:
fio: io_uring_cmd: /dev/<devnode>: status=0x4
> io_uring: Add .errdetails to parse CQ status

- t/run-fio-tests.py
Recently, three test case definitions were added to t/run-fio-tests. The added definitions have redundant pre_success lines. Remove them.
> t/run-fio-tests: remove redundant pre_success lines

- Makefile
- t/read-to-pipe-async.c
When NDEBUG is defined this was trying to call log_err but it didn't include the header file or link against the relevant .o file. This will now fully build with -DNDEBUG.
> t/read-to-pipe-async: fix -DNDEBUG support

- HOWTO.rst
- fio.1
Add missing limitation of verify_mode=compare in io_uring_cmd ioengine.  Data verification with NVMe COMPARE command has been introduced in Commit 6170d92a61da ("io_uring: Support Compare command for verification") and this should have documented COMPARE command only supports in case of data pattern verification.
The two more options should be with --verify_mode=compare.
verify_mode=compare
verify=pattern
verify_pattern=<pattern>
1. First line is a commit title, a descriptive one-liner for the change
2. Empty second line
3. Commit message body that explains why the change is useful. Break lines that
aren't something like a URL at 72-74 chars.
4. Empty line
5. Signed-off-by: Real Name <real@email.com>
Reminders:
1. If you …
> docs: update docs for verify_mode=compare of io_uring_cmd

- os/windows/posix.c
The Windows poll function does not clear revents field before it is populated.  As a result, subsequent calls to poll using the same pollfd reference return with revents set even when there is nothing available to read.  This later results in a hang in recv().
> Fix hang on Windows when multiple --client args are present

- oslib/blkzoned.h
Commit 4175f4dbec5d ("oslib: blkzoned: add blkzoned_move_zone_wp() helper function") introduced the new function for Linux, but did not add its stub function for OSes that lack the blkzoned feature. This caused build failures on MacOS and Windows. Add the missing stub to fix it.
Fixes: 4175f4dbec5d ("oslib: blkzoned: add blkzoned_move_zone_wp() helper function")
This PR fixes [the compile error reported on the list](https://lore.kernel.org/fio/a4728f95-f894-4ee3-80e9-674635848806@kernel.dk/T/#me7176f5f61ce01ea60fd657d55fdd6fbbf22423b).
> oslib: blkzoned: add missing blkzoned_move_zone_wp() stub

- engines/io_uring.c
When Protection Information (PI) is enabled on NVMe devices, the file size was incorrectly calculated using `data->lba_size` instead of `data->lba_ext`. This caused FIO to access only a portion of the device(e.g. 4096/(4096+64)=98.46%), leading to incomplete I/O coverage during tests.
This patch updates the `real_file_size` calculation logic to conditionally use `data->lba_ext` when available, and fall back to `data->lba_size` otherwise. This ensures that FIO correctly calculates the full storage capacity and accesses the entire device area when PI is enabled.
- Incomplete device access in FIO when PI is enabled
- Incorrect `real_file_size` assignment due to using `lba_size` instead of `lba_ext`
> io_uring: ensure accurate real_file_size setup for full device access with PI enabled

- parse.c
Use minimal distance to delimiter to determine option length
Current implementation of `opt_len()` function is using array of possible delimiters for option name search.
They are `{',', ':'}`.
The loop at https://github.com/axboe/fio/blob/813445e7129240d51216e396a5ba8e19296b6581/parse.c#L484 takes first found delimiter and return without trying to search by the rest of possibilities.
This causes `__handle_option()` function to falsely include into option name all chars up to first ',' ignoring any ':' chars.
Resulting not possible to parse options like `zoned:50/5:30/15:20/,50/10:50/90`.
Fixes: https://github.com/axboe/fio/issues/1923
Signed-off-by: Leonid Kozlov <leonid.e.kozlov@gmail.com>
> Fix: parse.c opt_len() to use minimal distance to delimiter to determine option length

- io_u.c
For randtrimwrite, we should issue trim + write pair and those offsets should be same.
This works good for cases without `offset=` option, but not for cases with `offset=` option.  In cases with `offset=` option, it's necessary to subtract `file_offset`, which is value of `offset=` option, when calculationg offset of write.
This is a bit confusing because `last_start` is an actual offset that has already been issued through trim.  However, `last_start` is the value to which `file_offset` is added.  Since we add back `file_offset` later on after calling `get_next_block` in `get_next_offset`, `last_start` should be adjusted.
> io_u: fix offset calculation in randtrimwrite

- HOWTO.rst
- engines/http.c
- fio.1
Security tokens are an element of S3 authorization in some environments. This change adds a parameter to allow users to specify a security token, and pass this to S3 requests with the appropriate header.
> engines/http: Add S3 security token support

- io_u.c
As Commit 813445e71292 ('backend: clean up requeued io_u's') has been applied, backend cleans up the remained io_u's in td->io_u_requeues. However, with end_fsync=1, the __get_io_u() function returns an io_u from td->io_u_requeues if any io_u exist, and pops it. This leads that the synced io_u will not put file which it got, and, finally, cannot close the file.
This patch returns io_u from td->io_u_free_list when td->runstate is TD_FSYNCING, so that the io_u's in td->io_u_requeues will be cleaned up and leads to close file appropriately.
> io_u: get io_u from io_u_freelist when TD_FSYNCING

- arch/arch.h
- engines/io_uring.c
- Fix `fio_ioring_getevents()` incorrectly decreasing the `max` number of events
- Only load the CQ `tail` index once for the full batch of available CQEs
- Simplify the control flow in `fio_ioring_getevents()`
- Justify advancing the CQ `tail` index before reading the CQEs, and relax the ordering of the atomic store
> io_uring CQ reap cleanup

- Makefile
> Makefile: fix man and share install paths on macOS

- fio.h
- t/verify-state.c
- verify-state.h
- Improve verify state inflight output that is dumped by t/fio-verify-state
- Synchronise verify state version in t/verify-state.c so it works with state files produced by the current fio and will automatically pick up future verify state version bumps
> t/verify-state.c fixes/improvements

- Makefile
- os/mac/posix.c
- os/mac/posix.h
- os/os-mac.h
The current behavior of flushing the pagecache via `posix_fadvise(POSIX_FADV_DONTNEED)` is not a valid operation on macOS. 
This can result in adverse outcomes when measuring performance. The change will instead flush via `mmap` and `msync`, which better reflects the desired behavior on macOS
> Improve flushing pagecache on darwin

- crc/test.c
- lib/memcpy.c
Include `os/os.h` before `fio_time.h` in the header files. Fixes #1993.
> test, memcpy: reorder #includes to use platform-specific code
