ioengines.c
Signed-off-by: David Disseldorp <ddiss@suse.de>
=> ioengine: remove duplicate queue handler check

engines/rdma.c
In order to ease debugging it would be nice to know why certain
rdma/ib functions fail. I've added %m messages to a large
number of log_err lines.
=> Modify RDMA engine to print strerror messages.

Makefile, configure, engines/pmemblk.c, examples/pmemblk.fio
Seeking comments on a new IO engine utilizing the NVML libpmemblk.  More information on libpmemblk and the NVML is available here http://pmem.io/nvml/.
=> add pmemblk engine

tools/fiologparser.py
This is cleaned-up version of PR 176.  I added a new option to fiologparser.py, -A, to generate more useful stats from latency logs. I think it's a great idea to divide up the latency log into time intervals, but I wasn't getting a good picture of the latency distribution. This option generates a csv format that can be directly loaded into a spreadsheet and graphed. For example, if I run it on a real latency log with thousands of records, it looks like this:
[ben@bene-laptop ceph]$ ./fiologparser.py -A example-latency.log | head > [example.csv](https://s3.amazonaws.com/ben.england/fiologparser/example-latency.csv)
which can be loaded directly into a [LibreOffice spreadsheet](https://s3.amazonaws.com/ben.england/fiologparser/example-latency-graph.ods) and a [graph of it generated with …
=> add -A option for better stats

fio.1, gettime-thread.c, idletime.c, memory.c, options.c
Posted to fio mailinglist already, but you can also pull from here, Jens. Thanks, Martin
=> Spellingfixes

tools/fiologparser.py
Signed-off-by: Mark Nelson <mnelson@redhat.com>
=> fiologparser.py: remove numpy and scipy dependency

tools/fio.service
I put it under tools for lack of better idea.
Comments appreciated.
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
=> add simple fio.service to start fio server with systemd

engines/rbd.c
Signed-off-by: Pan Liu <pan.liu@istuary.com>
=> rbd: remove duplicate _fio_rbd_connect

server.h
=> server: bump protocol version

README
A package is provided into Arch Linux repos
=> <README/pkg: Add reference to Arch Linux package>

engines/rbd.c
Signed-off-by: Pan Liu <wanjun.lp@alibaba-inc.com>
=> return correct error code for unhandled addr.

init.c
Just the presence of io_ops isn't enough - the requested ioengine may have changed.
This fixes number 5 from issue #408. The other problems identified in that issue still remain and would probably take a much bigger set of changes.
Signed-off-by: Ben Walker <benjamin.walker@intel.com>
=> Correctly detect whether ioengine_load can exit early

engines/windowsaio.c
The existing code for selecting whether sequential or random I/O is used seems a bit strange in engines/windowsaio.c. This commit makes it mirror what's done over in td_io_open_file() of ioengines.c. I passed up the chance to stick an `assert(0)` on the default: case to again mirror what is done elsewhere - let me know if this was wrong.
=> windowsaio: obey sequential/random I/O hinting

client.c
After running the scan-build from clang, I produce the following fixes.
=> Several fixes

engines/windowsaio.c
https://stackoverflow.com/questions/478340/clear-file-cache-to-repeat-perf`ormance-testing/7113153#7113153
mentions that opening a file without buffering on Windows has the side
effect of flushing cached parts of the file out of RAM. Use this side
effect to do cache invalidation on non-direct jobs that are using the
windowsaio engine. Note this invalidation will fail if the file is also
open elsewhere and we can't check whether we have exclusive access
without introducing a race where other jobs fail while we temporarily
have exclusive access to the file.
Preliminary pull request to gather suggestions and feedback.
=> windowsaio: add best effort invalidation

examples/fio-rand-RW.job, examples/fio-rand-read.job, examples/fio-rand-write.job, examples/fio-seq-RW.job, examples/fio-seq-read.job, examples/fio-seq-write.job
Adding support for multiple jobs for fio test, adding 6 job files.
Signed-off-by: Venu <venutiwa@in.ibm.com>
=> Adding support for multiple jobs for fio test

HOWTO, Makefile, configure, engines/libpmem.c, examples/libpmem.fio, fio.1, options.c
Adding an ioengine that access with the libpmem as memory
through a memory mmaped file on DAX filesystem.
It's very similar to the mmap engine and the dev-dax engine.
=> Add libpmem ioengine

configure
check for rbd_invaidate_cache() --> check for rbd_invalidate_cache()
Signed-off-by: Enming Zhang <enming.zhang@umcloud.com>
=> configure: fix typos

Makefile, configure, engines/rados.c, examples/rados.fio, fio.1
Signed-off-by: Igor Fedotov <ifedotov@suse.com>
=> Add support for Ceph Rados benchmarking.

HOWTO
Signed-off-by: Igor Fedotov <ifedotov@suse.com>
=> Update HOWTO with RADOS information

configure
=> Refer to zlib-static package in zlib static build warning

smalloc.c
Since it can happen that memory allocated with smalloc() is freed by
a child process and since Valgrind's memory tracking is per process
the smalloc()/sfree() instrumentation leads to incorrect Valgrind
reports. Hence remove that instrumentation again.
Fixes: 0ffccc21fcd6 ("Improve Valgrind instrumentation of memory allocations")
Signed-off-by: Bart Van Assche <bart.vanassche@wdc.com>
=> smalloc: Remove Valgrind instrumentation

compiler/compiler.h, flist.h, minmax.h, oslib/libmtd_common.h, verify.c
so we are able to extend fio with C++ .
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
=> replace typeof with __typeof__

os/os-windows.h
=> platforms/windows: Add S_ISSOCK macro.

filesetup.c, ioengines.c
Problem occurs when processing generated iolog files, such as this:
fio version 2 iolog
rbd_data.0 add
rbd_data.0 open
rbd_data.0 write 0 4096
rbd_data.0 close
rbd_data.0 open
rbd_data.0 write 0 4096
rbd_data.0 close
=> iolog replay: Treat 'open' on file that is scheduled to close as cancel of 'close' operation.

HOWTO, fio.1, tools/fio.service
A small bunch of documentation changes and some minor tweaks to the systemd .service file.
=> Minor fixes

configure
Signed-off-by: David Disseldorp <ddiss@suse.de>
=> configure: avoid pkg-config usage for http engine

lib/axmap.c
While I was verifying the axmap implementation I documented what is nontrivial and I also implemented a few small optimizations.
=> Document and optimize the axmap implementation

backend.c, client.c, diskutil.c, fio.h, init.c, stat.c
Addressed feedback from the first iteration. No other changes were made.
=> 20180823 terse remote fix

tools/hist/fio-histo-log-pctiles.py
DNM yet, want to give it some wider testing first.
see [issue 676](https://github.com/axboe/fio/issues/676)  for change details
=> handle log_unix_epoch=1

HOWTO, fio.1
Jens, here is the documentation update requested in #687
=> docs: clarify usage of steadystate detection feature

tools/hist/fio-histo-log-pctiles.py
This change was triggered by integration with [pbench](https://github.com/distributed-system-analysis/pbench) but should be useful to others.  This calculation does not work for a small enough sample count.   The output format change is not backward-compatible change, if this is a problem let me know, but I think this should not be a big issue at this point where not many applications are parsing output of this program. Output now looks like this:
```
msec-since-start, samples, min, median, 90.0, 95.0, 99.0, max, 
0,        0, , , , , , , 
2000,      392, 8.0, 11.9214545455, 15.0646518519, 292.2496, 696.89344, 761.856
4000,      399, 6.976, 10.9718158936, 14.0618981662, 15.0542178183, 17.0315329838, 761.856
6000,      792, 6.976, 11.9043493415, 15.0058790567, 16.0169657658, 499.957657343, …
```
=> add rsp. time samples as column 2, use meaningful pctile names

arch/arch-x86-common.h
Add Hygon SoC VendorID checking for Hygon Dhyana CPU to detect and enable tsc_reliable feature
=> Add Hygon SoC support to enable tsc_reliable feature

HOWTO, Makefile, configure, engines/libiscsi.c, examples/libiscsi.fio, filesetup.c, fio.1, optgroup.h
Adding a new engine that access iscsi lun with libiscsi.
Signed-off-by: Kyle Zhang <kyle@smartx.com>
=> fio: add libiscsi engine

tools/plot/fio2gnuplot
Closes #804
Signed-off-by: Alexander Kapshuna <kapsh@kap.sh>
=> fio2gnuplot: fix TabErrors when running with Python 3

engines/rados.c
=> engines/rados: changed polling to completion callbacks methodology

Makefile, unittests/oslib/strcasestr.c, unittests/oslib/strsep.c, unittests/unittest.c, unittests/unittest.h
Add some unittests to the framework I've written a year ago.
There were no bugs found this time, so nothing interesting here, just adding test cases.
=> unittests: add unittests for oslib/{strcasestr,strsep}.c

.gitignore, gclient.c, stat.c, t/run-fio-tests.py
Jens, please consider these four patches that represent minor cleanups/changes.
=> Four minor patches

.travis.yml, zbd.c
Jens, this pull request resolves the following issues:
- Windows build issue from yesterday https://ci.appveyor.com/project/axboe/fio/builds/32027846
- macOS xcode11.2 testing issue with scipy https://travis-ci.org/github/axboe/fio/jobs/672339101
The travis-ci changelog announced an xcode11.2 image change two weeks ago which contained an issue with python which was ultimately resolved a couple days ago: https://changelog.travis-ci.com/xcode-11-3-1-xcode-11-2-1-xcode-11-1-and-xcode11-images-updated-142286
=> Resolve Windows build, macOS testing issues

Makefile
=> Add fio-histo-log-pctiles to make file

t/btrace2fio.c
Single fio job cannot do read/write and trim. Generate two separate jobs
for pid that does both read/write and trim: pidxxx and pidxxx_trim.
Signed-off-by: Song Liu <songliubraving@fb.com>
=> btrace2fio: create separate jobs for pid with both read/write and trim

tools/plot/fio2gnuplot
On behalf of @gkunz
Fixes #989 - fio2gnuplot dont generate clat (raw) plots
=> Corrected scope of for-loop

Makefile, lib/num2str.c, unittests/lib/num2str.c, unittests/unittest.c, unittests/unittest.h
This pull request includes several small patches that improve num2str().
=> Improve num2str()

workqueue.c
Since test t0013 often hangs on Travis and Appveyor, I analyzed these hangs further. My conclusion is that these hangs are caused by race conditions in the workqueue mechanism. Hence this pull request.
=> Fix race conditions in the workqueue mechanism

io_u.c, stat.c
Fixes: https://github.com/axboe/fio/issues/1039
io_u: fix asymptotically high time run in accordance with blocksize of fio when using rate with timeout
stat: Adding changes to check and convert rs->agg[ddir] in KBytes
io_u:
Check if the usec is taking negative values.
However it is unlikely, But still a possibility.
If this is not taken care, usec_sleep() can take a
huge nap which is capable of not exiting the process indefinitely
although the process/thread may be sleeping
Signed-off-by: Sriharsha B S <sribs@microsoft.com>
=> io_u: fix exit failure case when using rates and timeout

compiler/compiler.h, configure
So I know you've merged something already to address this but I was fiddling with about with this in the morning to check if it worked. I figure I'll post it for posterity even if it doesn't get merged (I'd have to rebase it anyway).
=> configure: check for C11 atomics support

.appveyor.yml, ci/travis-build.sh, t/run-fio-tests.py
Jens, please consider this series of patches that make a handful of small improvements to the testing code.
=> Test cleanups

.travis.yml, Makefile, ci/travis-build.sh, ci/travis-install.sh, configure, memory.c
- Enable the cuda and libiscsi ioengines in travis (this way we get at least compile time testing)
- Fix up bugs found by the above
- Add a search for a differently named tcmalloc
- Cosmetic changes
=> Travis cleanup

HOWTO, fio.1, init.c, iolog.c
Fixes: #997
Signed-off-by: Shundong Zhou <donny372@gmail.com>
=> init/iolog: add support for reading iolog from stdin

init.c
https://github.com/axboe/fio/pull/1019 added support for reading iolog from stdin, but we could have multiple instance of reading iolog, only one can read from stdin.
=> Avoid multiple instances read iolog from stdin.

Makefile, configure
The (fairly old!) GUASI engine didn't build but these fixes seemed to get it working again. I doubt it's an engine that sees much use these days but amazingly it still works if you get all the pieces...
=> Makefile/configure: fix guasi build

.appveyor.yml, Makefile, ci/appveyor-install.sh, ci/travis-build.sh, ci/travis-install.sh, configure, engines/net.c, engines/windowsaio.c, os/windows/cpu-affinity.c, os/windows/dobuild.cmd, os/windows/install.wxs, os/windows/posix.c, t/memlock.c
Mostly changes around Windows as found by Windows clang, changes to support generating Windows PDB debug symbols and a few CI cleanups.
=> PDB, Windows fixes, CI improvements

configure, engines/posixaio.c, fio_time.h, gettime.c, gettime.h, helper_thread.c, stat.c, stat.h, steadystate.c, steadystate.h
Make the interval timer more accurate.
=> Rework the interval timer code

goptions.c
Signed-off-by: Jiahao Li gloit042@gmail.com
=> goptions: correct postfix

filesetup.c
Fixes https://github.com/axboe/fio/issues/1132
=> filesetup: reword block size too large message

server.c
this is my second try.
this time I'm sure there is an error.
the essence of the error lies in a possible hit in the eternal cycle while, when exiting the higher cycle by means of break.
keeping in mind your requirements, I will immediately ask for help in describing the functionality of the place I am correcting, so that I can create tests and poc. with less effort.
thank
Signed-off-by: Sergey Valentey <ihsinme@gmail.com>
=> fix loop with unreachable exit condition

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/axboe/fio/1190)
=> Add /t/fuzz/fuzz_parseini to .gitignore

os/os-android.h
Android add support for NDK sharedmem since API level 26 and prohibit the directly use of ashmem since API level 29, so we can use sharedmem if targeting API level is higher than 26.
Please refer to the Android official document: [Behavior changes: apps targeting API 29+](https://developer.android.com/about/versions/10/behavior-changes-10#shared-memory)
=> android: add support for NDK sharedmem

engines/exec.c
As per the coverty reports, there was some issues in my code :
- Some structures were not properly freed before returning.
- Some file descriptors were not properly closed
- Testing with 'if (!int)' isn't a good way to test if the value is negative
Signed-off-by: Erwan Velu <erwanaliasr1@gmail.com>
=> engines/exec: Code cleanup to remove leaks

server.c
For some custom ioengines (see https://github.com/spdk/spdk/issues/1118), it's not trivial to suppress output to stdout and stderr, so they would write to some other file descriptor fio had opened - which is bad.
This change ensures that fd's 0, 1, and 2 (stdin, stdout, stderr) are always valid and can be used without any unintended consequences.
=> server: reopen standard streams to /dev/null

HOWTO
=> fixed typo in HOWTO

engines/sg.c, filesetup.c, lib/fls.h, log.c, stat.c, zbd.c
This PR was done after running scan-build to detect useless variable assignments and a null pointer issue.
=> Code cleanup

t/one-core-peak.sh
Two commits here, 
- one to fix the memory reporting
- one to use the latency feature in the reporting
=> Latencies  + memory fix

t/one-core-peak.sh
Fixing some bash syntax,
Reporting kernel configuration
Reporting low level nvme features
=> Improving one-peak

t/one-core-peak.sh
A few little tweaks to t/one-core-peak.sh
- The [default](https://github.com/axboe/fio/blob/25425cb4a5531b1b3f26eba4e49866d944e0f1fb/t/io_uring.c#L97) number of threads in the benchmark is 1.
- When only one block device is passed, use one of the cores in its Numa domain instead of the first core.
CC @ErwanAliasr1
=> Tweaks to t/one-core-peak.sh

README.md
- Updated README to README.md to make it look nicer when rendered on Github.
=> Update README to markdown format

client.c, engines/windowsaio.c, init.c, optgroup.h, os/os-windows.h, os/windows/posix.c, server.c, server.h
This fork has two high level changes
1) Windows --server support
2) New command line option to align windowsaio with linuxaio's threading model and improve IOP/s.
=> Windows server support and performance improvement

tools/genfio
Originally submitted as https://www.spinics.net/lists/fio/msg09881.html, rebased here.
=> genfio: fix temporary file handling

configure
- fixed typo in configure script
=> fixed typo in configure script

ci/actions-full-test.sh
the script might be called with 'sudo' from the call site, if required
=> actions-full-test.sh, removed sudo from the script

HOWTO.rst, fio.1
Fixes: https://github.com/axboe/fio/issues/1443
=> doc: clarify that I/O errors may go unnoticed without direct=1

backend.c
When closing a command prompt window or terminating it using something
like the taskkill command, each child process (such as a running FIO
workload) is sent a SIGBREAK signal. Once those child processes have
responded to that signal, Windows terminates them if they're still
executing.
This change has the main thread to wait for others to exit when handling
a SIGBREAK signal, such that each job will still have time to wrap-up
and give stats before the entire program terminates.
Signed-off-by: Brandon Paupore <brandon.paupore@wdc.com>
=> Add wait for handling SIGBREAK

init.c
Refs https://github.com/scop/bash-completion/pull/777#discussion_r956535980
=> init: include 5 in --terse-version help

fio.1
fix spelling error
Signed-off-by: lilinjie <lilinjie@uniontech.com>
=> fix spelling error

README.rst
=> Fixes typos/grammar

configure, os/windows/dlls.c, os/windows/posix/include/syslog.h
Enable support for --zonemode=zbd on Android.
1. First line is a commit title, a descriptive one-liner for the change
2. Empty second line
3. Commit message body that explains why the change is useful. Break lines that
aren't something like a URL at 72-74 chars.
4. Empty line
5. Signed-off-by: Real Name <real@email.com>
=> Android: Enable zoned block device support

HOWTO.rst
Update documentation typo
Signed-off-by: chienfuchen32 <chienfuchen32@gmail.com>
=> Update documentation typo

blktrace.c
make operation error:make error on 'uos' system
Blktrace file make operation error ’undefined reference to `major'‘ Problems on uos system
liuyafei@uniontech.com
=> make operation error:make error on 'uos' system

backend.c, cairo_text_helpers.c, cairo_text_helpers.h, engines/io_uring.c, goptions.h, ioengines.c, log.c, options.c
some files require to have some missing headers included
=> fix missing headers in multiple files

client.c, client.h
protect variables and parameters from programmer's point of view with 'constness'
=> use 'const' where it is required

ioengines.c
* ioengines prints error log when got I/O error
- close #1572
=> ioengines: Make td_io_queue print log_err when got error

os/os-qnx.h
This makes `os_physmem` work on QNX 7.1 and 8.0.
- On QNX 7.1 it was returning an uninitialized value since `sysctl({CTL_HW, HW_PHYSMEM64}, ...)` always fails with `ENOENT`.
- On QNX 8.0 it didn't build because `HW_PHYSMEM64` isn't defined.
This yanks the `sysctl` and instead sums up the sizes of all `ram` areas in the syspage's `asinfo` array. It's what QNX recommends with the deprecation of `uint32_t ramsize` in the syspage's `system_private` entry ([QNX 6.4.1 source](https://github.com/vocho/openqnx/blob/cc95df3543a1c481d4f8ad387e29f0d1ff0c87fe/trunk/services/system/public/sys/syspage.h#L295)).
`fio` now detects the same size in MiB as `top` shows in its `Memory total` column on both QNX 7.1 and 8.0.
=> QNX: Fix physical memory detection

engines/dfs.c
dfs engine mistakenly used a symbol named 'dfs' to call dlsym(dlhandle, engine_lib), this symbol points a global variable in dfs.c file. I change this variable name to 'daosfs' to point to 'ioengine' symbol correctly.
Fixes: https://github.com/axboe/fio/issues/1874
Signed-off-by: fugen <fugen@cstor.cn>
=> dfs: fix fail to load dfs engine

HOWTO.rst, README.rst, examples/http-s3.fio
Add important info about http_host and file formatting to s3 example
Will save future folks from having to debug the same thing I did.
=> Add important info about http_host and file formatting to s3 example

engines/io_uring.c
fio_ioring_queue() bails out if the SQ's tail + 1 == head. This will always be false, since 0 <= tail - head <= entries. Probably it was meant to check whether the SQ is full, i.e. tail == head + entries. (The head index should be loaded with acquire ordering in that case.) Checking for a full SQ isn't necessary anyways, as the prior check for ld->queued == td->o.iodepth already ensures the SQ isn't full.
So remove the unnecessary and misleading tail + 1 == head check.
=> engines/io_uring: remove unnecessary SQ full check

engines/io_uring.c
Currently, the call to validate metadata at the end of fio_ioring_event is unreachable.
Move the call within the success path, and clean up indentation by removing a redundant if statement.
=> engines/io_uring: validate PI on read
